/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package gui;

import nguyenvu.components.SimpleForm;

/**
 *
 * @author HP
 */
public class BanHang extends SimpleForm {
    /**
     * Creates new customizer BanHang
     */
    public BanHang() {
        initComponents();
    }
    
    private void init() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTimKiem = new javax.swing.JPanel();
        pnContent = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        pnTimKiem.setBackground(new java.awt.Color(11, 101, 136));
        pnTimKiem.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnTimKiem.setPreferredSize(new java.awt.Dimension(100, 40));
        pnTimKiem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(pnTimKiem, java.awt.BorderLayout.PAGE_START);
        add(pnContent, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnContent;
    private javax.swing.JPanel pnTimKiem;
    // End of variables declaration//GEN-END:variables
}
