/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.toedter.calendar.JDateChooser;
import dao.BaoCaoSanPhamBanCham_DAO;
import dao.BaoCaoSanPhamBanChay_DAO;
import entity.BaoCaoSanPhamBanChay_enity;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileOutputStream;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import nguyenvu.components.SimpleForm;

import org.apache.poi.ss.usermodel.*; // Các lớp cơ bản để tạo và định dạng Excel
import org.apache.poi.xssf.usermodel.XSSFWorkbook; // Làm việc với file .xlsx
import org.apache.poi.ss.util.CellRangeAddress;
// 650 1120
/**
 *
 * @author Vovan
 */
public class BaoCaoSanPhamBanCham_Panel extends javax.swing.JPanel {

        private int currentPage = 1;
        private int rowsPerPage = 10;
        private int totalPages = 0;
        private BaoCaoSanPhamBanCham_DAO dao;
        private JDialog dateDialog;
        private Date selectedStartDate;
        private Date selectedEndDate;
        private int selected;
        private List<BaoCaoSanPhamBanChay_enity> reportData;
        
        private LocalDate ngayHienTai = LocalDate.now();
        private LocalDate bayNgayTruoc = ngayHienTai.minusDays(7);
        private LocalDate bamuoiNgayTruoc = ngayHienTai.minusDays(30);
        private LocalDate chinmuoiNgayTruoc = ngayHienTai.minusDays(90);
        private LocalDate basaunamngaytruoc = ngayHienTai.minusDays(365);

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        SimpleDateFormat formatterForDate = new SimpleDateFormat("dd/MM/yyyy");
    /**
     * Creates new form BaoCaoSanPham_Panel
     */
    public BaoCaoSanPhamBanCham_Panel(int select) {
        initComponents();
        if(select == 0 || select == 7 || select == 30 || select == 90
                || select == 365 || select == 0){
            loadData(currentPage, rowsPerPage, select);
            addActionListeners(select);
            this.selected = select;
        } else {
            showCustomDateRange();
            loadDataTuyChinh(selectedStartDate, selectedEndDate);
            addActionListeners(select);
            this.selected = select;
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnFirst = new javax.swing.JButton(new FlatSVGIcon("gui/icon/first-lblPageIndicator.svg", 0.03f));
        btnPrevious = new javax.swing.JButton(new FlatSVGIcon("gui/icon/prev.svg"));
        btnNext = new javax.swing.JButton(new FlatSVGIcon("gui/icon/next.svg"));
        btnLast = new javax.swing.JButton(new FlatSVGIcon("gui/icon/last-lblPageIndicator.svg", 0.03f));
        lblPageIndicator = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1120, 650));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Loại sản phẩm", "Giá", "Tổng số lượng bán"
            }
        ));
        table.setRowHeight(60);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
		centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
		for (int i = 0; i < table.getColumnCount(); i++) {
		    table.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
		}
        jScrollPane1.setViewportView(table);

        btnFirst.setIcon(new FlatSVGIcon("gui/icon/first-page.svg",0.02f));
        btnPrevious.setIcon(new FlatSVGIcon("gui/icon/pre-page.svg",0.01f));
        btnNext.setIcon(new FlatSVGIcon("gui/icon/next-page.svg",0.01f));
        btnLast.setIcon(new FlatSVGIcon("gui/icon/last-page.svg",0.02f));

        lblPageIndicator.setText("page");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPageIndicator)
                .addGap(32, 32, 32)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(770, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnLast, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNext, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPrevious, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFirst, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPageIndicator))
                .addGap(46, 46, 46))
        );
    }// </editor-fold>                        
    
    public void loadData(int currentPage, int rowsPerPage, int select) {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) table.getModel();
        model.setRowCount(0); // Xóa dữ liệu bảng

        dao = new BaoCaoSanPhamBanCham_DAO();
        ArrayList<BaoCaoSanPhamBanChay_enity> dsBaoCao = dao.getAllBaoCaoSanPhamBanCham(select);

        totalPages = (int) Math.ceil((double) dsBaoCao.size() / rowsPerPage);

        int start = (currentPage - 1) * rowsPerPage;
        int end = Math.min(start + rowsPerPage, dsBaoCao.size());

        for (int i = start; i < end; i++) {
            BaoCaoSanPhamBanChay_enity bc = dsBaoCao.get(i);
            Object[] rowData = {
                bc.getMaSP(),
                bc.getTenSP(),
                bc.getLoaiSP(),
                String.format("%.2f", bc.getGia()),
                bc.getSlBan()
            };
            model.addRow(rowData);
        }

        lblPageIndicator.setText(currentPage + " / " + totalPages);
    }
    
    public void loadDataTuyChinh(Date from, Date to ) {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) table.getModel();
        model.setRowCount(0); // Xóa dữ liệu bảng

        dao = new BaoCaoSanPhamBanCham_DAO();
        ArrayList<BaoCaoSanPhamBanChay_enity> dsBaoCao = dao.getSanPhamBanChamTuyChinh(from, to);

        totalPages = (int) Math.ceil((double) dsBaoCao.size() / rowsPerPage);

        int start = (currentPage - 1) * rowsPerPage;
        int end = Math.min(start + rowsPerPage, dsBaoCao.size());

        for (int i = start; i < end; i++) {
            BaoCaoSanPhamBanChay_enity bc = dsBaoCao.get(i);
            Object[] rowData = {
                bc.getMaSP(),
                bc.getTenSP(),
                bc.getLoaiSP(),
                String.format("%.2f", bc.getGia()),
                bc.getSlBan()
            };
            model.addRow(rowData);
        }

        lblPageIndicator.setText(currentPage + " / " + totalPages);
    }

    public void showCustomDateRange() {
            if (dateDialog == null) { // Chỉ tạo dialog một lần
            // Tạo một panel để chứa JDateChooser và nút Xác Nhận
            JPanel datePanel = new JPanel();
            datePanel.setLayout(new BoxLayout(datePanel, BoxLayout.Y_AXIS));

            // Tạo JPanel chứa JLabel và căn trái
            JPanel panelStartDate = new JPanel(new FlowLayout(FlowLayout.LEFT));
            JLabel nbd = new JLabel("Ngày Bắt Đầu:");
            panelStartDate.add(nbd);
            datePanel.add(panelStartDate);

            // Tạo và thêm JDateChooser cho ngày bắt đầu
            JDateChooser dateChooserStart = new JDateChooser();
            datePanel.add(dateChooserStart);

            // Tạo JPanel chứa JLabel và căn trái
            JPanel panelEndDate = new JPanel(new FlowLayout(FlowLayout.LEFT));
            JLabel nkt = new JLabel("Ngày Kết Thúc:");
            panelEndDate.add(nkt);
            datePanel.add(panelEndDate);

            // Tạo và thêm JDateChooser cho ngày kết thúc
            JDateChooser dateChooserEnd = new JDateChooser();
            datePanel.add(dateChooserEnd);

            // Tạo JPanel cho nút xác nhận và căn phải
            JPanel panelButton = new JPanel(new FlowLayout(FlowLayout.RIGHT));
            JButton btnConfirm = new JButton("Xác Nhận");
            panelButton.add(btnConfirm);
            datePanel.add(panelButton);

            // Đặt màu nền cho panel là tím nhạt
            datePanel.setBackground(new Color(240, 240, 240));

            // Hộp thoại tùy chỉnh JOptionPane
            dateDialog = new JDialog((Frame) null, "Chọn Ngày", true);
            dateDialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            dateDialog.getContentPane().add(datePanel);
            dateDialog.pack();
            dateDialog.setSize(250, 200);
            dateDialog.setLocationRelativeTo(null);

            // Xử lý sự kiện xác nhận
            btnConfirm.addActionListener(new ActionListener() {
                
                @Override
                public void actionPerformed(ActionEvent e) {
                    java.util.Date startDate = dateChooserStart.getDate();
                    java.util.Date endDate = dateChooserEnd.getDate();

                    if (startDate != null && endDate != null) {
                        if (startDate.after(endDate)) {
                            JOptionPane.showMessageDialog(dateDialog, "Ngày bắt đầu không được sau ngày kết thúc.");
                            return;
                        }

                        // Cập nhật giá trị vào các biến toàn cục
                        selectedStartDate = startDate;
                        selectedEndDate = endDate;

                        // Định dạng ngày sang chuỗi dd/MM/yyyy
                        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                        String formattedStartDate = dateFormat.format(startDate);
                        String formattedEndDate = dateFormat.format(endDate);

                        String customDateRange = formattedStartDate + " - " + formattedEndDate;

                        dateDialog.dispose(); // Ẩn dialog
                    } else {
                        JOptionPane.showMessageDialog(dateDialog, "Vui lòng chọn đầy đủ ngày bắt đầu và kết thúc.");
                    }
                }
            });
        }

        // Hiển thị dialog
        dateDialog.setVisible(true);
    }
    private void addActionListeners(int select) {
        btnFirst.addActionListener(e -> {
            if (currentPage > 1) {
                currentPage = 1;
                if(select == 0 || select == 7 || select == 30 || select == 90
                || select == 365 || select == 0){
            loadData(currentPage, rowsPerPage, select);
        } else {
            loadDataTuyChinh(selectedStartDate, selectedEndDate);
        }
            }
        });

        btnPrevious.addActionListener(e -> {
            if (currentPage > 1) {
                currentPage--;
                if(select == 0 || select == 7 || select == 30 || select == 90
                || select == 365 || select == 0){
            loadData(currentPage, rowsPerPage, select);
        } else {
            loadDataTuyChinh(selectedStartDate, selectedEndDate);
        }
            }
        });

        btnNext.addActionListener(e -> {
            if (currentPage < totalPages) {
                currentPage++;
               if(select == 0 || select == 7 || select == 30 || select == 90
                || select == 365 || select == 0){
            loadData(currentPage, rowsPerPage, select);
        } else {
            loadDataTuyChinh(selectedStartDate, selectedEndDate);
        }
            }
        });

        btnLast.addActionListener(e -> {
            if (currentPage < totalPages) {
                currentPage = totalPages;
                if(select == 0 || select == 7 || select == 30 || select == 90
                || select == 365 || select == 0){
            loadData(currentPage, rowsPerPage, select);
        } else {
            loadDataTuyChinh(selectedStartDate, selectedEndDate);
        }
            }
        });
    }
    
    public void xuatPDF() {
    try {
        // Tạo đối tượng Font cho tiêu đề và nội dung
        BaseFont baseFont = BaseFont.createFont("/gui/vi/Times New Roman Regular.ttf", BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
        Font titleFont = new Font(baseFont, 20, Font.BOLD);  // Font cho tiêu đề
        Font contentFont = new Font(baseFont, 12, Font.NORMAL);  // Font cho nội dung bảng
        Font tenQuayFont = new Font(baseFont, 13, Font.BOLD);
        Font thoiGianFont = new Font(baseFont, 13, Font.BOLD);

        // Tạo file PDF
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Chọn nơi lưu file PDF");
        int userSelection = fileChooser.showSaveDialog(null);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            if (!fileToSave.getAbsolutePath().endsWith(".pdf")) {
                fileToSave = new File(fileToSave.getAbsolutePath() + ".pdf");
            }

            // Khởi tạo đối tượng Document
            Document document = new Document(PageSize.A4);
            PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream(fileToSave));

            // Mở file PDF
            document.open();

            // Tiêu đề báo cáo
            Paragraph tenQuay = new Paragraph("Quầy thuốc DRUGSOFT", tenQuayFont);
            tenQuay.setAlignment(Element.ALIGN_LEFT);
            document.add(tenQuay);

            Paragraph title = new Paragraph("Báo cáo sản phẩm bán chạy", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            document.add(title);

            // Thêm thông tin khoảng thời gian
            Paragraph form;
            if (selected == 7) {
                form = new Paragraph("Từ " + bayNgayTruoc.format(formatter) + " tới " + ngayHienTai.format(formatter), thoiGianFont);
            } else if (selected == 30) {
                form = new Paragraph("Từ " + bamuoiNgayTruoc.format(formatter) + " tới " + ngayHienTai.format(formatter), thoiGianFont);
            } else if (selected == 90) {
                form = new Paragraph("Từ " + chinmuoiNgayTruoc.format(formatter) + " tới " + ngayHienTai.format(formatter), thoiGianFont);
            } else if (selected == 365) {
                form = new Paragraph("Từ " + basaunamngaytruoc.format(formatter) + " tới " + ngayHienTai.format(formatter), thoiGianFont);
            } else if (selected == 0) {
                form = new Paragraph("Từ trước đến giờ", thoiGianFont);
            } else {
                form = new Paragraph("Từ " + formatterForDate.format(selectedStartDate) + " tới " + formatterForDate.format(selectedEndDate), thoiGianFont);
            }
            form.setAlignment(Element.ALIGN_CENTER);
            document.add(form);

            document.add(new Paragraph(" "));

            // Lấy dữ liệu báo cáo
            if (selected == 7) {
                reportData = dao.getAllBaoCaoSanPhamBanCham(7);
            } else if (selected == 30) {
                reportData = dao.getAllBaoCaoSanPhamBanCham(30);
            } else if (selected == 90) {
                reportData = dao.getAllBaoCaoSanPhamBanCham(90);
            } else if (selected == 365) {
                reportData = dao.getAllBaoCaoSanPhamBanCham(365);
            } else if (selected == 0) {
                reportData = dao.getAllBaoCaoSanPhamBanCham(0);
            } else {
                reportData = dao.getSanPhamBanChamTuyChinh(selectedStartDate, selectedEndDate);
            }

            // Tạo bảng PDF
            PdfPTable pdfTable = new PdfPTable(5); // 5 cột: Mã SP, Tên SP, Loại SP, Giá, Số lượng bán
            pdfTable.setWidthPercentage(100);
            pdfTable.setSpacingBefore(10f);
            pdfTable.setSpacingAfter(10f);

            // Thêm tiêu đề bảng với font tùy chỉnh
            String[] headers = {"Mã sản phẩm", "Tên sản phẩm", "Loại sản phẩm", "Giá", "Tổng số lượng bán"};
            for (String header : headers) {
                PdfPCell cell = new PdfPCell(new Phrase(header, tenQuayFont));
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                cell.setBackgroundColor(BaseColor.LIGHT_GRAY);
                pdfTable.addCell(cell);
            }

            // Thêm dữ liệu vào bảng PDF
            DecimalFormat df = new DecimalFormat("#,###");
            for (BaoCaoSanPhamBanChay_enity item : reportData) {
                pdfTable.addCell(item.getMaSP());
                pdfTable.addCell(item.getTenSP());
                pdfTable.addCell(item.getLoaiSP());
                pdfTable.addCell(df.format(item.getGia()));
                pdfTable.addCell(String.valueOf(item.getSlBan()));
            }

            // Thêm bảng vào document
            document.add(pdfTable);

            // Thêm thông tin người lập báo cáo
            Paragraph thoiGian = new Paragraph("Ngày " + ngayHienTai.getDayOfMonth() + " tháng " +
                    ngayHienTai.getMonthValue() + " năm " + ngayHienTai.getYear(), thoiGianFont);
            thoiGian.setAlignment(Element.ALIGN_RIGHT);
            thoiGian.setIndentationRight(10f);
            document.add(thoiGian);

            Paragraph nguoiLap = new Paragraph("Người lập báo cáo", thoiGianFont);
            nguoiLap.setAlignment(Element.ALIGN_RIGHT);
            nguoiLap.setIndentationRight(40f);
            document.add(nguoiLap);

            Paragraph kyTen = new Paragraph("(Ký họ tên)", thoiGianFont);
            kyTen.setAlignment(Element.ALIGN_RIGHT);
            kyTen.setIndentationRight(55f);
            document.add(kyTen);

            // Đóng tài liệu PDF
            document.close();

            // Thông báo thành công
            JOptionPane.showMessageDialog(null, "Đã xuất file PDF thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Lỗi khi xuất file PDF: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
}
    
    public void xuatExcel() {
    try {
        // Tạo file Excel
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Chọn nơi lưu file Excel");
        int userSelection = fileChooser.showSaveDialog(null);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            if (!fileToSave.getAbsolutePath().endsWith(".xlsx")) {
                fileToSave = new File(fileToSave.getAbsolutePath() + ".xlsx");
            }

            // Khởi tạo workbook và sheet
            Workbook workbook = new XSSFWorkbook();
            Sheet sheet = workbook.createSheet("Báo cáo sản phẩm bán chạy");

            // Tạo kiểu định dạng cho tiêu đề và cột
            CellStyle titleCellStyle = workbook.createCellStyle();
            titleCellStyle.setAlignment(HorizontalAlignment.CENTER);
            titleCellStyle.setVerticalAlignment(VerticalAlignment.CENTER);

            CellStyle headerCellStyle = workbook.createCellStyle();
            headerCellStyle.setAlignment(HorizontalAlignment.CENTER);
            headerCellStyle.setVerticalAlignment(VerticalAlignment.CENTER);
            headerCellStyle.setFillForegroundColor(IndexedColors.LIGHT_YELLOW.getIndex());
            headerCellStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);

            CellStyle contentCellStyle = workbook.createCellStyle();
            contentCellStyle.setAlignment(HorizontalAlignment.LEFT);

            // Tiêu đề báo cáo
            Row titleRow = sheet.createRow(0);
            Cell titleCell = titleRow.createCell(0);
            titleCell.setCellValue("Báo cáo sản phẩm bán chạy");
            titleCell.setCellStyle(titleCellStyle);
            sheet.addMergedRegion(new CellRangeAddress(0, 0, 0, 4));

            // Thêm thông tin thời gian
            Row timeRow = sheet.createRow(1);
            Cell timeCell = timeRow.createCell(0);
            String thoiGian;
            if (selected == 7) {
                thoiGian = "Từ " + bayNgayTruoc.format(formatter) + " tới " + ngayHienTai.format(formatter);
            } else if (selected == 30) {
                thoiGian = "Từ " + bamuoiNgayTruoc.format(formatter) + " tới " + ngayHienTai.format(formatter);
            } else if (selected == 90) {
                thoiGian = "Từ " + chinmuoiNgayTruoc.format(formatter) + " tới " + ngayHienTai.format(formatter);
            } else if (selected == 365) {
                thoiGian = "Từ " + basaunamngaytruoc.format(formatter) + " tới " + ngayHienTai.format(formatter);
            } else if (selected == 0) {
                thoiGian = "Từ trước đến giờ";
            } else {
                thoiGian = "Từ " + formatterForDate.format(selectedStartDate) + " tới " + formatterForDate.format(selectedEndDate);
            }
            timeCell.setCellValue(thoiGian);
            sheet.addMergedRegion(new CellRangeAddress(1, 1, 0, 4));

            // Thêm tiêu đề cột
            String[] headers = {"Mã sản phẩm", "Tên sản phẩm", "Loại sản phẩm", "Giá", "Tổng số lượng bán"};
            Row headerRow = sheet.createRow(3);
            for (int i = 0; i < headers.length; i++) {
                Cell headerCell = headerRow.createCell(i);
                headerCell.setCellValue(headers[i]);
                headerCell.setCellStyle(headerCellStyle);
            }

            // Lấy dữ liệu báo cáo
            List<BaoCaoSanPhamBanChay_enity> reportData;
            if (selected == 7) {
                reportData = dao.getAllBaoCaoSanPhamBanCham(7);
            } else if (selected == 30) {
                reportData = dao.getAllBaoCaoSanPhamBanCham(30);
            } else if (selected == 90) {
                reportData = dao.getAllBaoCaoSanPhamBanCham(90);
            } else if (selected == 365) {
                reportData = dao.getAllBaoCaoSanPhamBanCham(365);
            } else if (selected == 0) {
                reportData = dao.getAllBaoCaoSanPhamBanCham(0);
            } else {
                reportData = dao.getSanPhamBanChamTuyChinh(selectedStartDate, selectedEndDate);
            }

            // Thêm dữ liệu vào bảng
            int rowIndex = 4;
            DecimalFormat df = new DecimalFormat("#,###");
            for (BaoCaoSanPhamBanChay_enity item : reportData) {
                Row row = sheet.createRow(rowIndex++);
                row.createCell(0).setCellValue(item.getMaSP());
                row.createCell(1).setCellValue(item.getTenSP());
                row.createCell(2).setCellValue(item.getLoaiSP());
                row.createCell(3).setCellValue(df.format(item.getGia()));
                row.createCell(4).setCellValue(item.getSlBan());
            }

            // Tự động điều chỉnh độ rộng cột
            for (int i = 0; i < headers.length; i++) {
                sheet.autoSizeColumn(i);
            }

            // Ghi file ra đĩa
            FileOutputStream fileOut = new FileOutputStream(fileToSave);
            workbook.write(fileOut);
            fileOut.close();
            workbook.close();

            // Thông báo thành công
            JOptionPane.showMessageDialog(null, "Đã xuất file Excel thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Lỗi khi xuất file Excel: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
}


    
    // Variables declaration - do not modify                     
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPageIndicator;
    private javax.swing.JTable table;
    // End of variables declaration                   
}
