/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package gui;

import entity.DonTam_entity;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import nguyenvu.components.SimpleForm;
import raven.alerts.MessageAlerts;

/**
 *
 * @author HP
 */
public class DialogTempOrderProcess extends SimpleForm{
    private JPopupMenu popupMenu;
    private List<DonTam_entity> listDonTam;
    private BanHang banHang;
    
    public DialogTempOrderProcess(JPopupMenu popupMenu, BanHang banHang) {
        this.banHang = banHang;
        this.popupMenu = popupMenu;
        listDonTam = new ArrayList<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableTemp = new javax.swing.JTable();
        btnCancel = new javax.swing.JButton();
        btnProcess = new javax.swing.JButton();

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách đơn tạm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(11, 101, 136))); // NOI18N

        tableTemp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SDT", "Tên khách hàng", "Danh sách sản phẩm", "Thời gian lưu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTemp.setRowHeight(60);
        tableTemp.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableTemp);
        if (tableTemp.getColumnModel().getColumnCount() > 0) {
            tableTemp.getColumnModel().getColumn(0).setResizable(false);
            tableTemp.getColumnModel().getColumn(0).setPreferredWidth(100);
            tableTemp.getColumnModel().getColumn(1).setResizable(false);
            tableTemp.getColumnModel().getColumn(1).setPreferredWidth(180);
            tableTemp.getColumnModel().getColumn(2).setResizable(false);
            tableTemp.getColumnModel().getColumn(2).setPreferredWidth(300);
            tableTemp.getColumnModel().getColumn(3).setResizable(false);
            tableTemp.getColumnModel().getColumn(3).setPreferredWidth(100);
        }

        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancel.setText("Hủy");
        btnCancel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(11, 101, 136), 1, true));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnProcess.setBackground(new java.awt.Color(11, 101, 136));
        btnProcess.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnProcess.setForeground(new java.awt.Color(255, 255, 255));
        btnProcess.setText("Xử lý");
        btnProcess.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 954, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        if(popupMenu != null) {
            popupMenu.setVisible(false);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // TODO add your handling code here:
        DonTam_entity selectedDonTam = getSelectedDonTam();
        if (selectedDonTam != null) {
            banHang.loadDonTam(selectedDonTam);
            removeSelectedDonTam();
            popupMenu.setVisible(false);
            this.setVisible(false);
        } 
        else {
            MessageAlerts.getInstance().showMessage("Lỗi", "Chọn đơn tạm để xử lý!", MessageAlerts.MessageType.ERROR);
        }
    }//GEN-LAST:event_btnProcessActionPerformed
  
    public void themDonTam(DonTam_entity donTam) {
        listDonTam.add(donTam);
        capNhatBangTemp();
    }

    public void capNhatBangTemp() {
        DefaultTableModel model = (DefaultTableModel) tableTemp.getModel();
        model.setRowCount(0);
        for (DonTam_entity donTam : listDonTam) {
            model.addRow(new Object[]{
                donTam.getSdtKH(),
                donTam.getTenKH(),
                donTam.getListSP().size() + " sản phẩm",
                new java.util.Date(donTam.getThoiGianLuu())
            });
        }
    }
    
    public DonTam_entity getSelectedDonTam() {
        int selectedRow = tableTemp.getSelectedRow();
        if (selectedRow >= 0) {
            return listDonTam.get(selectedRow);
        }
        return null; 
    }
    
    public void removeSelectedDonTam() {
        int selectedRow = tableTemp.getSelectedRow();
        if (selectedRow >= 0) {
            listDonTam.remove(selectedRow);
            ((DefaultTableModel) tableTemp.getModel()).removeRow(selectedRow);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnProcess;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableTemp;
    // End of variables declaration//GEN-END:variables
}
