/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import javax.swing.table.DefaultTableModel;
import nguyenvu.components.SimpleForm;

/**
 *
 * @author Vovan
 */
public class KhachHang extends SimpleForm {

    /**
     * Creates new form KhachHang
     */
    public KhachHang() {
        initComponents();
        
        DefaultTableModel model = (DefaultTableModel) tbKhachHang.getModel();
    Object[][] data = {
        {"1", "KH01", "Văn Vĩ", "Nam", "0123456789", "Hoạt động"},
        {"2", "KH02", "Ngọc Uyên", "Nữ", "0987654321", "Ngừng hoạt động"},
        {"3", "KH03", "Nguyên Vũ", "Nam", "0912345678", "Hoạt động"},
        {"4", "KH04", "Minh Khang", "Nam", "0934567890", "Hoạt động"}
    };

    for (Object[] row : data) {
        model.addRow(row);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnContent = new javax.swing.JPanel();
        pnHead = new javax.swing.JPanel();
        lblHead = new javax.swing.JLabel();
        tfTim = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        spBang = new javax.swing.JScrollPane();
        tbKhachHang = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(1500, 800));
        setLayout(new java.awt.BorderLayout());

        pnContent.setMinimumSize(new java.awt.Dimension(1500, 800));
        pnContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnHead.setBackground(new java.awt.Color(255, 255, 255));
        pnHead.setMinimumSize(new java.awt.Dimension(1500, 60));
        pnHead.setPreferredSize(new java.awt.Dimension(1500, 60));

        lblHead.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        lblHead.setText("Khách Hàng");

        tfTim.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        tfTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTimActionPerformed(evt);
            }
        });

        btnTim.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnHeadLayout = new javax.swing.GroupLayout(pnHead);
        pnHead.setLayout(pnHeadLayout);
        pnHeadLayout.setHorizontalGroup(
            pnHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeadLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblHead, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(tfTim, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnTim)
                .addContainerGap(412, Short.MAX_VALUE))
        );
        pnHeadLayout.setVerticalGroup(
            pnHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeadLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pnHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHead)
                    .addComponent(tfTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pnContent.add(pnHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 110));

        tbKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã khách hàng", "Tên khách hàng", "Giới tính", "Số điện thoại", "Hoạt động"
            }
        ));
        spBang.setViewportView(tbKhachHang);

        pnContent.add(spBang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 1460, 670));

        add(pnContent, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        String keyword = tfTim.getText().trim().toLowerCase(); // Lấy từ khóa và chuyển về chữ thường
    if (keyword.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập số điện thoại hoặc tên khách hàng cần tìm!");
        return;
    }

    DefaultTableModel model = (DefaultTableModel) tbKhachHang.getModel();
    DefaultTableModel filteredModel = new DefaultTableModel(
        new Object[]{"STT", "Mã khách hàng", "Tên khách hàng", "Giới tính", "Số điện thoại", "Hoạt động"},
        0
    );

    boolean found = false;

    // Duyệt qua tất cả các dòng trong bảng để tìm kiếm
    for (int i = 0; i < model.getRowCount(); i++) {
        String tenKhachHang = model.getValueAt(i, 2).toString().toLowerCase();
        String soDienThoai = model.getValueAt(i, 4).toString();

        // Nếu tìm thấy từ khóa trong tên hoặc số điện thoại
        if (tenKhachHang.contains(keyword) || soDienThoai.contains(keyword)) {
            filteredModel.addRow(new Object[]{
                model.getValueAt(i, 0),
                model.getValueAt(i, 1),
                model.getValueAt(i, 2),
                model.getValueAt(i, 3),
                model.getValueAt(i, 4),
                model.getValueAt(i, 5)
            });
            found = true;
        }
    }

    if (found) {
        tbKhachHang.setModel(filteredModel); // Hiển thị chỉ các dòng tìm thấy
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Không tìm thấy khách hàng với từ khóa: " + keyword);
    }
    }//GEN-LAST:event_btnTimActionPerformed

    private void tfTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTimActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTim;
    private javax.swing.JLabel lblHead;
    private javax.swing.JPanel pnContent;
    private javax.swing.JPanel pnHead;
    private javax.swing.JScrollPane spBang;
    private javax.swing.JTable tbKhachHang;
    private javax.swing.JTextField tfTim;
    // End of variables declaration//GEN-END:variables
}
