/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import connectDB.connectDB;
import dao.KhachHang_DAO;
import entity.KhachHang_entity;
import gui.vi.ButtonEditorKhachHang;
import gui.vi.ButtonRenderer;
import java.awt.Image;
import java.text.Collator;
import java.util.List;
import java.util.Locale;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import nguyenvu.components.SimpleForm;


public class KhachHang_GUI extends SimpleForm {

    private KhachHang_DAO khachHangDAO = new KhachHang_DAO();
    private String soDTGoc;
    private ButtonGroup groupTheoTen;
    private ButtonGroup groupGioiTinh;
    
    /**
     * Creates new form KhachHang
     */
    public KhachHang_GUI() {
        initComponents();
        dieuChinhCBBGioiTinh();
        taiDuLieuLenBang();
        themNutChinhSuaVaXoa();
        themIconChoNut();
        radioLoc();
        suKienLoc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of Qthis method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlChinhSua = new javax.swing.JDialog();
        pnChinhSua = new javax.swing.JPanel();
        pnHeadChinhSua = new javax.swing.JPanel();
        lblHeadChinhSua = new javax.swing.JLabel();
        lblHoTenKHChinhSua = new javax.swing.JLabel();
        tfHoTenKhChinhSua = new javax.swing.JTextField();
        lblSDTKHChinhSua = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        lblGioiTinhKHCHinhSua = new javax.swing.JLabel();
        cbGioiTinh = new javax.swing.JComboBox<>();
        btnHuy = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        dlThem = new javax.swing.JDialog();
        pnThem = new javax.swing.JPanel();
        pnHeadThem = new javax.swing.JPanel();
        lblHeadThem = new javax.swing.JLabel();
        lblHoTenThem = new javax.swing.JLabel();
        lblSDTThem = new javax.swing.JLabel();
        lblGioiTinhThem = new javax.swing.JLabel();
        btnDlHuy = new javax.swing.JButton();
        btnDlThem = new javax.swing.JButton();
        tfHoTenThem = new javax.swing.JTextField();
        tfSDTThem = new javax.swing.JTextField();
        cbGioiTinhThem = new javax.swing.JComboBox<>();
        pnContent = new javax.swing.JPanel();
        pnHead = new javax.swing.JPanel();
        lblHead = new javax.swing.JLabel();
        tfTim = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        spBang = new javax.swing.JScrollPane();
        tbKhachHang = new javax.swing.JTable();
        pnLoc = new javax.swing.JPanel();
        btnKhoiPhuc = new javax.swing.JButton();
        pnSapXep = new javax.swing.JPanel();
        radioAtoZ = new javax.swing.JRadioButton();
        radioZtoA = new javax.swing.JRadioButton();
        pnGioiTinh = new javax.swing.JPanel();
        radioNam = new javax.swing.JRadioButton();
        radioNu = new javax.swing.JRadioButton();

        pnChinhSua.setBackground(new java.awt.Color(255, 255, 255));
        pnChinhSua.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnHeadChinhSua.setBackground(new java.awt.Color(255, 255, 255));
        pnHeadChinhSua.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N

        lblHeadChinhSua.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        lblHeadChinhSua.setText("Khách hàng / Chỉnh sửa thông tin");

        javax.swing.GroupLayout pnHeadChinhSuaLayout = new javax.swing.GroupLayout(pnHeadChinhSua);
        pnHeadChinhSua.setLayout(pnHeadChinhSuaLayout);
        pnHeadChinhSuaLayout.setHorizontalGroup(
            pnHeadChinhSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeadChinhSuaLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lblHeadChinhSua, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(514, Short.MAX_VALUE))
        );
        pnHeadChinhSuaLayout.setVerticalGroup(
            pnHeadChinhSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeadChinhSuaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblHeadChinhSua)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pnChinhSua.add(pnHeadChinhSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 60));

        lblHoTenKHChinhSua.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        lblHoTenKHChinhSua.setText("Họ và tên");
        pnChinhSua.add(lblHoTenKHChinhSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 100, -1));

        tfHoTenKhChinhSua.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        pnChinhSua.add(tfHoTenKhChinhSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 710, 40));

        lblSDTKHChinhSua.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblSDTKHChinhSua.setText("Số điện thoại");
        pnChinhSua.add(lblSDTKHChinhSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 120, -1));

        jTextField1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        pnChinhSua.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 710, 40));

        lblGioiTinhKHCHinhSua.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblGioiTinhKHCHinhSua.setText("Giới tính ");
        pnChinhSua.add(lblGioiTinhKHCHinhSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 130, 30));

        cbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam ", "Nữ" }));
        pnChinhSua.add(cbGioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 252, 710, 40));

        btnHuy.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnHuy.setText("Hủy");
        pnChinhSua.add(btnHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 120, 40));

        btnLuu.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        pnChinhSua.add(btnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 110, 40));

        dlChinhSua.getContentPane().add(pnChinhSua, java.awt.BorderLayout.CENTER);

        dlThem.setPreferredSize(new java.awt.Dimension(1000, 500));

        pnThem.setBackground(new java.awt.Color(255, 255, 255));
        pnThem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnHeadThem.setBackground(new java.awt.Color(255, 255, 255));

        lblHeadThem.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        lblHeadThem.setText("Khách hàng / Thêm khách hàng");

        javax.swing.GroupLayout pnHeadThemLayout = new javax.swing.GroupLayout(pnHeadThem);
        pnHeadThem.setLayout(pnHeadThemLayout);
        pnHeadThemLayout.setHorizontalGroup(
            pnHeadThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeadThemLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lblHeadThem, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnHeadThemLayout.setVerticalGroup(
            pnHeadThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeadThemLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblHeadThem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnThem.add(pnHeadThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 70));

        lblHoTenThem.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblHoTenThem.setText("Họ và tên");
        pnThem.add(lblHoTenThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        lblSDTThem.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblSDTThem.setText("Số điện thoại");
        pnThem.add(lblSDTThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        lblGioiTinhThem.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblGioiTinhThem.setText("Giới tính");
        pnThem.add(lblGioiTinhThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        btnDlHuy.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btnDlHuy.setText("Hủy");
        btnDlHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDlHuyActionPerformed(evt);
            }
        });
        pnThem.add(btnDlHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 401, 150, 40));

        btnDlThem.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btnDlThem.setText("Thêm");
        btnDlThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDlThemActionPerformed(evt);
            }
        });
        pnThem.add(btnDlThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, 150, 40));

        tfHoTenThem.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        pnThem.add(tfHoTenThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 690, 40));

        tfSDTThem.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        pnThem.add(tfSDTThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 690, 40));

        cbGioiTinhThem.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        cbGioiTinhThem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        pnThem.add(cbGioiTinhThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 690, 40));

        dlThem.getContentPane().add(pnThem, java.awt.BorderLayout.CENTER);

        setMinimumSize(new java.awt.Dimension(1500, 800));
        setLayout(new java.awt.BorderLayout());

        pnContent.setMinimumSize(new java.awt.Dimension(1500, 800));
        pnContent.setPreferredSize(new java.awt.Dimension(1500, 800));
        pnContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnHead.setBackground(new java.awt.Color(255, 255, 255));
        pnHead.setMinimumSize(new java.awt.Dimension(1500, 60));
        pnHead.setPreferredSize(new java.awt.Dimension(1500, 60));

        lblHead.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        lblHead.setText("Khách Hàng");

        tfTim.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N

        btnTim.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnHeadLayout = new javax.swing.GroupLayout(pnHead);
        pnHead.setLayout(pnHeadLayout);
        pnHeadLayout.setHorizontalGroup(
            pnHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeadLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblHead, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(tfTim, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        pnHeadLayout.setVerticalGroup(
            pnHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeadLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pnHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHead)
                    .addComponent(tfTim, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pnContent.add(pnHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 1500, 110));

        tbKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên khách hàng", "Số điện thoại", "Điểm thưởng", "Giới tính", "Cập nhật", "Xóa"
            }
        ));
        spBang.setViewportView(tbKhachHang);

        pnContent.add(spBang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 1100, 670));

        pnLoc.setBackground(new java.awt.Color(255, 255, 255));
        pnLoc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lọc Khách Hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 18))); // NOI18N

        btnKhoiPhuc.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btnKhoiPhuc.setText("Khôi phục");

        pnSapXep.setBackground(new java.awt.Color(255, 255, 255));
        pnSapXep.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sắp xếp theo tên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 18))); // NOI18N

        radioAtoZ.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        radioAtoZ.setText("A - Z");

        radioZtoA.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        radioZtoA.setText("Z - A");

        javax.swing.GroupLayout pnSapXepLayout = new javax.swing.GroupLayout(pnSapXep);
        pnSapXep.setLayout(pnSapXepLayout);
        pnSapXepLayout.setHorizontalGroup(
            pnSapXepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSapXepLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(pnSapXepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioZtoA)
                    .addComponent(radioAtoZ))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnSapXepLayout.setVerticalGroup(
            pnSapXepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSapXepLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(radioAtoZ)
                .addGap(44, 44, 44)
                .addComponent(radioZtoA)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pnGioiTinh.setBackground(new java.awt.Color(255, 255, 255));
        pnGioiTinh.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Giới tính", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 18))); // NOI18N

        radioNam.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        radioNam.setText("Nam");

        radioNu.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        radioNu.setText("Nữ");

        javax.swing.GroupLayout pnGioiTinhLayout = new javax.swing.GroupLayout(pnGioiTinh);
        pnGioiTinh.setLayout(pnGioiTinhLayout);
        pnGioiTinhLayout.setHorizontalGroup(
            pnGioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGioiTinhLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pnGioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioNu)
                    .addComponent(radioNam))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnGioiTinhLayout.setVerticalGroup(
            pnGioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGioiTinhLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(radioNam)
                .addGap(44, 44, 44)
                .addComponent(radioNu)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnLocLayout = new javax.swing.GroupLayout(pnLoc);
        pnLoc.setLayout(pnLocLayout);
        pnLocLayout.setHorizontalGroup(
            pnLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLocLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnGioiTinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnSapXep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pnLocLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(btnKhoiPhuc, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        pnLocLayout.setVerticalGroup(
            pnLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLocLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(pnSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(btnKhoiPhuc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pnContent.add(pnLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 110, 370, 640));

        add(pnContent, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
            int selectedRow = tbKhachHang.getSelectedRow();  // Lấy dòng được chọn
            if (selectedRow >= 0) {
                // Loại bỏ khoảng trắng ở đầu và cuối của các chuỗi
                String tenKH = tfHoTenKhChinhSua.getText().trim();
                String soDTMoi = jTextField1.getText().trim();
                String gioiTinh = cbGioiTinh.getSelectedItem().toString().trim();

                // Kiểm tra độ dài của từng chuỗi trước khi cập nhật
                if (tenKH.length() > 50) {
                    tenKH = tenKH.substring(0, 50);  // Cắt chuỗi nếu vượt quá 50 ký tự
                }
                if (soDTMoi.length() > 10) {
                    soDTMoi = soDTMoi.substring(0, 10);  // Cắt chuỗi nếu vượt quá 10 ký tự
                }
                if (gioiTinh.length() > 10) {
                    gioiTinh = gioiTinh.substring(0, 10);  // Cắt chuỗi nếu vượt quá 10 ký tự
                }

                try {
                    // Tạo đối tượng khách hàng với dữ liệu đã làm sạch
                    KhachHang_entity khachHang = new KhachHang_entity(tenKH, soDTMoi, 0, gioiTinh);

                    // Cập nhật dữ liệu trong CSDL thông qua DAO
                    boolean isUpdated = khachHangDAO.capNhatKhachHang(khachHang, soDTGoc);

                    if (isUpdated) {
                        JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
                        taiDuLieuLenBang();  // Tải lại dữ liệu lên bảng
                        dlChinhSua.setVisible(false);  // Đóng form
                    } else {
                        JOptionPane.showMessageDialog(this, "Cập nhật thất bại!");
                    }
                } catch (Exception ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật dữ liệu!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn một khách hàng để cập nhật.");
            }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        String keyword = tfTim.getText().trim(); // Lấy từ khóa tìm kiếm từ TextField

        if (keyword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số điện thoại hoặc tên khách hàng để tìm kiếm.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tbKhachHang.getModel();
        model.setRowCount(0); // Xóa dữ liệu cũ trong bảng trước khi hiển thị kết quả mới

        List<KhachHang_entity> danhSachKhachHang;

        // Kiểm tra nếu keyword là số (tìm theo SDT) hoặc chuỗi (tìm theo tên)
        if (keyword.matches("\\d+")) { // Nếu keyword là số
            KhachHang_entity kh = khachHangDAO.timKhachHangTheoSDT(keyword);
            if (kh != null) {
                // Thêm khách hàng vào bảng nếu tìm thấy
                model.addRow(new Object[]{1, kh.getTenKH(), kh.getsdtKH(), kh.getDiemThuong(), kh.getGioiTinh()});
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy khách hàng với số điện thoại: " + keyword);
            }
        } else { // Nếu không phải số, tìm theo tên
            danhSachKhachHang = khachHangDAO.timKhachHangTheoTen(keyword);
            if (danhSachKhachHang.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy khách hàng với tên: " + keyword);
            } else {
                int stt = 1;
                // Thêm tất cả khách hàng tìm thấy vào bảng
                for (KhachHang_entity kh : danhSachKhachHang) {
                    model.addRow(new Object[]{stt++, kh.getTenKH(), kh.getsdtKH(), kh.getDiemThuong(), kh.getGioiTinh()});
                }
            }
        }
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnDlThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDlThemActionPerformed
        // Lấy dữ liệu từ các trường nhập liệu
        String tenKH = tfHoTenThem.getText().trim();
        String soDT = tfSDTThem.getText().trim();
        String gioiTinh = cbGioiTinhThem.getSelectedItem().toString().trim();

        // Kiểm tra ràng buộc dữ liệu
        if (tenKH.isEmpty() || tenKH.length() > 50) {
            JOptionPane.showMessageDialog(this, "Tên khách hàng không được để trống và phải dưới 50 ký tự.");
            return;
        }

        if (soDT.isEmpty() || !soDT.matches("\\d{10}")) {
            JOptionPane.showMessageDialog(this, "Số điện thoại phải có đúng 10 chữ số.");
            return;
        }

        if (!(gioiTinh.equals("Nam") || gioiTinh.equals("Nữ"))) {
            JOptionPane.showMessageDialog(this, "Giới tính phải là Nam hoặc Nữ.");
            return;
        }

        // Nếu dữ liệu hợp lệ, tạo đối tượng KhachHang và gọi phương thức thêm vào CSDL
        KhachHang_entity khachHang = new KhachHang_entity(tenKH, soDT, 0, gioiTinh); // Điểm thưởng mặc định là 0

        boolean isAdded = khachHangDAO.themKhachHang(khachHang);

        if (isAdded) {
            JOptionPane.showMessageDialog(this, "Thêm khách hàng thành công!");
            taiDuLieuLenBang();  // Cập nhật lại bảng dữ liệu
            dlThem.setVisible(false);  // Đóng dialog thêm
        } else {
            JOptionPane.showMessageDialog(this, "Lỗi khi thêm khách hàng!");
        }
    }//GEN-LAST:event_btnDlThemActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
       hienThiDialogThem();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnDlHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDlHuyActionPerformed
         dlThem.setVisible(false);
    }//GEN-LAST:event_btnDlHuyActionPerformed
    private void dieuChinhCBBGioiTinh(){
       cbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
    }
    private void taiDuLieuLenBang() {
        DefaultTableModel model = (DefaultTableModel) tbKhachHang.getModel();
        model.setRowCount(0);  // Xóa tất cả các dòng cũ trong bảng

        try {
            List<KhachHang_entity> danhSachKhachHang = khachHangDAO.getTatCaKhachHang();
            int stt = 1;

            for (KhachHang_entity kh : danhSachKhachHang) {
                model.addRow(new Object[]{
                    stt++,
                    kh.getTenKH(),
                    kh.getsdtKH(),
                    kh.getDiemThuong(),
                    kh.getGioiTinh()
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu lên bảng!");
        }
    }

 
    

   
    private void themNutChinhSuaVaXoa() {
        // Tạo renderer và editor cho nút "Cập nhật"
        ButtonRenderer btnChinhSuaRenderer = new ButtonRenderer("/gui/icon/edit.png");
        ButtonEditorKhachHang btnChinhSuaEditor = new ButtonEditorKhachHang(
                "/gui/icon/edit.png", tbKhachHang, this, "edit");

        // Tạo renderer và editor cho nút "Xóa"
        ButtonRenderer btnXoaRenderer = new ButtonRenderer("/gui/icon/delete.png");
        ButtonEditorKhachHang btnXoaEditor = new ButtonEditorKhachHang(
                "/gui/icon/delete.png", tbKhachHang, this, "delete");

        // Thiết lập renderer và editor cho cột
        tbKhachHang.getColumnModel().getColumn(5).setCellRenderer(btnChinhSuaRenderer);
        tbKhachHang.getColumnModel().getColumn(5).setCellEditor(btnChinhSuaEditor);
        tbKhachHang.getColumnModel().getColumn(6).setCellRenderer(btnXoaRenderer);
        tbKhachHang.getColumnModel().getColumn(6).setCellEditor(btnXoaEditor);
    }

    private void themIconChoNut(){
        btnTim.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnTim.setText("       Tìm Kiếm"); // Thêm khoảng trắng để cân bằng
        btnTim.setIcon(resizeIcon("/gui/icon/tim.png", 20, 20)); // Resize icon
        btnTim.setHorizontalAlignment(javax.swing.SwingConstants.LEFT); // Căn icon sang trái
        btnTim.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT); // Đặt text bên phải icon
        btnTim.setIconTextGap(10); // Khoảng cách giữa icon và text
        btnTim.setPreferredSize(new java.awt.Dimension(220, 50)); // Điều chỉnh kích thước nút
        
        btnThem.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnThem.setText("       Thêm "); // Thêm khoảng trắng để cân bằng
        btnThem.setIcon(resizeIcon("/gui/icon/them.png", 20, 20)); // Resize icon
        btnThem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT); // Căn icon sang trái
        btnThem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT); // Đặt text bên phải icon
        btnThem.setIconTextGap(10); // Khoảng cách giữa icon và text
        btnThem.setPreferredSize(new java.awt.Dimension(220, 50)); // Điều chỉnh kích thước nút
        
        btnKhoiPhuc.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnKhoiPhuc.setText("      Khôi phục "); // Thêm khoảng trắng để cân bằng
        btnKhoiPhuc.setIcon(resizeIcon("/gui/icon/khoiphuc.png", 20, 20)); // Resize icon
        btnKhoiPhuc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT); // Căn icon sang trái
        btnKhoiPhuc.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT); // Đặt text bên phải icon
        btnKhoiPhuc.setIconTextGap(10); // Khoảng cách giữa icon và text
        btnKhoiPhuc.setPreferredSize(new java.awt.Dimension(220, 50)); // Điều chỉnh kích thước nút
        
        btnDlThem.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnDlThem.setText("      Thêm "); // Thêm khoảng trắng để cân bằng
        btnDlThem.setIcon(resizeIcon("/gui/icon/khoiphuc.png", 20, 20)); // Resize icon
        btnDlThem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT); // Căn icon sang trái
        btnDlThem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT); // Đặt text bên phải icon
        btnDlThem.setIconTextGap(10); // Khoảng cách giữa icon và text
        btnDlThem.setPreferredSize(new java.awt.Dimension(220, 50)); // Điều chỉnh kích thước nút

        btnDlHuy.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnDlHuy.setText("      Hủy "); // Thêm khoảng trắng để cân bằng
        btnDlHuy.setIcon(resizeIcon("/gui/icon/huy.png", 20, 20)); // Resize icon
        btnDlHuy.setHorizontalAlignment(javax.swing.SwingConstants.LEFT); // Căn icon sang trái
        btnDlHuy.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT); // Đặt text bên phải icon
        btnDlHuy.setIconTextGap(10); // Khoảng cách giữa icon và text
        btnDlHuy.setPreferredSize(new java.awt.Dimension(220, 50)); // Điều chỉnh kích thước nút
    }
    
    private ImageIcon resizeIcon(String path, int width, int height) {
        ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource(path));
        Image scaledImage = icon.getImage().getScaledInstance(width, height, java.awt.Image.SCALE_SMOOTH);
        return new javax.swing.ImageIcon(scaledImage);
    }

    public void hienThiThongTinKhachHang(int row) {
        String tenKH = (String) tbKhachHang.getValueAt(row, 1);
        soDTGoc = (String) tbKhachHang.getValueAt(row, 2);  // Lưu số điện thoại gốc
        int diemThuong = (int) tbKhachHang.getValueAt(row, 3);  // Điểm thưởng

        // Lấy và chuẩn hóa giới tính
        String gioiTinh = ((String) tbKhachHang.getValueAt(row, 4)).trim(); 

        // Điền dữ liệu vào các trường trong form chỉnh sửa
        tfHoTenKhChinhSua.setText(tenKH);
        jTextField1.setText(soDTGoc);

        // Kiểm tra giá trị giới tính và thiết lập trong JComboBox
        if (cbGioiTinh.getItemAt(0).equals(gioiTinh) || cbGioiTinh.getItemAt(1).equals(gioiTinh)) {
            cbGioiTinh.setSelectedItem(gioiTinh);  // Đặt giá trị hợp lệ
        } else {
            JOptionPane.showMessageDialog(this, "Giá trị giới tính không hợp lệ: " + gioiTinh);
        }

        // Hiển thị dialog chỉnh sửa
        dlChinhSua.pack();
        dlChinhSua.setLocationRelativeTo(this);  // Canh giữa màn hình
        chinhSuaKichThuocDialog(1000, 500);
        dlChinhSua.setVisible(true);  // Hiển thị dialog
    }



    
    public void xoaKhachHang(int row) {
        String soDT = (String) tbKhachHang.getValueAt(row, 2);  // Lấy số điện thoại từ dòng đã chọn

        try {
            boolean isDeleted = khachHangDAO.xoaKhachHang(soDT);  // Xóa qua DAO

            if (isDeleted) {
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
                taiDuLieuLenBang();  // Tải lại dữ liệu
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại!");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi xóa dữ liệu!");
        }
    }
    
    public void chinhSuaKichThuocDialog(int width, int height) {
        dlChinhSua.setSize(width, height); // Đặt kích thước mới cho dialog
        dlChinhSua.setLocationRelativeTo(this); // Canh giữa màn hình
    }
    
    private void radioLoc(){
        groupTheoTen = new ButtonGroup();
        groupTheoTen.add(radioAtoZ);
        groupTheoTen.add(radioZtoA);

        groupGioiTinh = new ButtonGroup();
        groupGioiTinh.add(radioNam);
        groupGioiTinh.add(radioNu);
    }

    private void locDuLieuKhachHang() {
        DefaultTableModel model = (DefaultTableModel) tbKhachHang.getModel();
        model.setRowCount(0); // Xóa dữ liệu cũ trong bảng trước khi hiển thị kết quả mới

        List<KhachHang_entity> danhSachKhachHang = khachHangDAO.getTatCaKhachHang();

        // Sắp xếp danh sách khách hàng theo tên riêng (từ cuối cùng) sử dụng Collator để so sánh theo tiếng Việt
        Collator collator = Collator.getInstance(new Locale("vi", "VN")); // Thiết lập Collator cho tiếng Việt

        if (radioAtoZ.isSelected()) {
            danhSachKhachHang.sort((kh1, kh2) -> collator.compare(layTenRieng(kh1.getTenKH()), layTenRieng(kh2.getTenKH())));
        } else if (radioZtoA.isSelected()) {
            danhSachKhachHang.sort((kh1, kh2) -> collator.compare(layTenRieng(kh2.getTenKH()), layTenRieng(kh1.getTenKH())));
        }

        // Lọc danh sách theo giới tính
        if (radioNam.isSelected()) {
            danhSachKhachHang.removeIf(kh -> !kh.getGioiTinh().equalsIgnoreCase("Nam"));
        } else if (radioNu.isSelected()) {
            danhSachKhachHang.removeIf(kh -> !kh.getGioiTinh().equalsIgnoreCase("Nữ"));
        }

        // Hiển thị dữ liệu đã lọc lên bảng
        int stt = 1;
        for (KhachHang_entity kh : danhSachKhachHang) {
            model.addRow(new Object[]{stt++, kh.getTenKH(), kh.getsdtKH(), kh.getDiemThuong(), kh.getGioiTinh()});
        }

        // Hiển thị thông báo nếu không tìm thấy kết quả nào
        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy khách hàng phù hợp với tiêu chí lọc.");
        }
    }



    private void suKienLoc(){
        radioAtoZ.addActionListener(evt -> locDuLieuKhachHang());
        radioZtoA.addActionListener(evt -> locDuLieuKhachHang());
        radioNam.addActionListener(evt -> locDuLieuKhachHang());
        radioNu.addActionListener(evt -> locDuLieuKhachHang());

        // Nút khôi phục
        btnKhoiPhuc.addActionListener(evt -> taiDuLieuLenBang());
    }
    
    private String layTenRieng(String hoTen) {
        String[] tenParts = hoTen.trim().split(" ");
        return tenParts[tenParts.length - 1];
    }
    
    private void hienThiDialogThem() {
        // Đặt kích thước cho dialog
        dlThem.setSize(1000, 500);
        // Đặt vị trí ở giữa màn hình
        dlThem.setLocationRelativeTo(this);
        // Hiển thị dialog
        dlThem.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDlHuy;
    private javax.swing.JButton btnDlThem;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnKhoiPhuc;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.JComboBox<String> cbGioiTinh;
    private javax.swing.JComboBox<String> cbGioiTinhThem;
    private javax.swing.JDialog dlChinhSua;
    private javax.swing.JDialog dlThem;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblGioiTinhKHCHinhSua;
    private javax.swing.JLabel lblGioiTinhThem;
    private javax.swing.JLabel lblHead;
    private javax.swing.JLabel lblHeadChinhSua;
    private javax.swing.JLabel lblHeadThem;
    private javax.swing.JLabel lblHoTenKHChinhSua;
    private javax.swing.JLabel lblHoTenThem;
    private javax.swing.JLabel lblSDTKHChinhSua;
    private javax.swing.JLabel lblSDTThem;
    private javax.swing.JPanel pnChinhSua;
    private javax.swing.JPanel pnContent;
    private javax.swing.JPanel pnGioiTinh;
    private javax.swing.JPanel pnHead;
    private javax.swing.JPanel pnHeadChinhSua;
    private javax.swing.JPanel pnHeadThem;
    private javax.swing.JPanel pnLoc;
    private javax.swing.JPanel pnSapXep;
    private javax.swing.JPanel pnThem;
    private javax.swing.JRadioButton radioAtoZ;
    private javax.swing.JRadioButton radioNam;
    private javax.swing.JRadioButton radioNu;
    private javax.swing.JRadioButton radioZtoA;
    private javax.swing.JScrollPane spBang;
    private javax.swing.JTable tbKhachHang;
    private javax.swing.JTextField tfHoTenKhChinhSua;
    private javax.swing.JTextField tfHoTenThem;
    private javax.swing.JTextField tfSDTThem;
    private javax.swing.JTextField tfTim;
    // End of variables declaration//GEN-END:variables
}
