/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import dao.TaiKhoan_DAO;
import gui.vi.ButtonEditor;
import gui.vi.ButtonRenderer;


import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import nguyenvu.components.SimpleForm;

/**

 */
public class TaiKhoan_GUI extends SimpleForm {
    private ButtonGroup groupPhanQuyen;
    private ButtonGroup groupTrangThai;
    private TaiKhoan_DAO taiKhoanDAO = new TaiKhoan_DAO();
    private TaiKhoan_GUI taiKhoan ;
    
    /**
     * Creates new form TaiKhoan
     */
    public TaiKhoan_GUI() {
        initComponents();
        initializeDatabase();
        radioLoc();
        setDefaultState();
        loadDataToTable(); 
}
    
    private void initializeDatabase() {
        connectDB.connectDB.accessDataBase();
}

    private void setDefaultState() {
        radioHoatDong.setSelected(true);  // Thiết lập trạng thái mặc định là 'Hoạt động'
        radioNgungHoatDong.setSelected(false);
        clearInputFields();  // Xóa nội dung các trường nhập liệu
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogEdit = new javax.swing.JDialog();
        pnEdit = new javax.swing.JPanel();
        lblTenTKEdit = new javax.swing.JLabel();
        lblMatKhauEdit = new javax.swing.JLabel();
        lblPhanQuyenEdit = new javax.swing.JLabel();
        lblTrangThaiEdit = new javax.swing.JLabel();
        tfMatKhauEdit = new javax.swing.JTextField();
        lblNhapLaiMatKhauEdit = new javax.swing.JLabel();
        tfNhapLaiMatKhauEdit = new javax.swing.JTextField();
        cbbPhanQuyenEdit = new javax.swing.JComboBox<>();
        cbbTrangThaiEdit = new javax.swing.JComboBox<>();
        btnHuyEdit = new javax.swing.JButton();
        btnLuuEdit = new javax.swing.JButton();
        pnHeadEdit = new javax.swing.JPanel();
        lblHeadEdit = new javax.swing.JLabel();
        tfTenTKEdit = new javax.swing.JTextField();
        pnContent = new javax.swing.JPanel();
        pnHeader = new javax.swing.JPanel();
        lblQuanLiTaiKhoan = new javax.swing.JLabel();
        tfTim = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        spTable = new javax.swing.JScrollPane();
        tableTK = new javax.swing.JTable();
        pnLoc = new javax.swing.JPanel();
        lblPhanQuyen = new javax.swing.JLabel();
        lblTrangThai = new javax.swing.JLabel();
        radioHoatDong = new javax.swing.JRadioButton();
        radioNgungHoatDong = new javax.swing.JRadioButton();
        radioQuanLy = new javax.swing.JRadioButton();
        radioNhanVien = new javax.swing.JRadioButton();
        btnKhoiPhuc = new javax.swing.JButton();
        pnThem = new javax.swing.JPanel();
        lblTenTaiKhoan = new javax.swing.JLabel();
        lblMatKhau = new javax.swing.JLabel();
        lblNhapLaiMatKhau = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfTenTaiKhoan = new javax.swing.JTextField();
        btnHuy = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        cbbPhanQuyen = new javax.swing.JComboBox<>();
        pfMatKhau = new javax.swing.JPasswordField();
        pfNhapLaiMatKhau = new javax.swing.JPasswordField();

        dialogEdit.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnEdit.setBackground(new java.awt.Color(255, 255, 255));

        lblTenTKEdit.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblTenTKEdit.setText("Tên tài khoản");

        lblMatKhauEdit.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblMatKhauEdit.setText("Mật khẩu");

        lblPhanQuyenEdit.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblPhanQuyenEdit.setText("Phân quyền");

        lblTrangThaiEdit.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblTrangThaiEdit.setText("Trạng thái");

        tfMatKhauEdit.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N

        lblNhapLaiMatKhauEdit.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblNhapLaiMatKhauEdit.setText("Nhập lại mật khẩu");

        tfNhapLaiMatKhauEdit.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N

        cbbPhanQuyenEdit.setBackground(new java.awt.Color(204, 204, 204));
        cbbPhanQuyenEdit.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        cbbPhanQuyenEdit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản lý", "Nhân viên" }));
        cbbPhanQuyenEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbPhanQuyenEditActionPerformed(evt);
            }
        });

        cbbTrangThaiEdit.setBackground(new java.awt.Color(204, 204, 204));
        cbbTrangThaiEdit.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        cbbTrangThaiEdit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hoạt động", "Ngừng hoạt động" }));

        btnHuyEdit.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnHuyEdit.setText("Hủy");

        btnLuuEdit.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnLuuEdit.setText("Lưu");
        btnLuuEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuEditActionPerformed(evt);
            }
        });

        pnHeadEdit.setBackground(new java.awt.Color(204, 204, 204));

        lblHeadEdit.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        lblHeadEdit.setText("Cập nhật thông tin tài khoản");

        javax.swing.GroupLayout pnHeadEditLayout = new javax.swing.GroupLayout(pnHeadEdit);
        pnHeadEdit.setLayout(pnHeadEditLayout);
        pnHeadEditLayout.setHorizontalGroup(
            pnHeadEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeadEditLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(lblHeadEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(323, Short.MAX_VALUE))
        );
        pnHeadEditLayout.setVerticalGroup(
            pnHeadEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeadEditLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblHeadEdit)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        tfTenTKEdit.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        tfTenTKEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTenTKEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnEditLayout = new javax.swing.GroupLayout(pnEdit);
        pnEdit.setLayout(pnEditLayout);
        pnEditLayout.setHorizontalGroup(
            pnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEditLayout.createSequentialGroup()
                .addGroup(pnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnEditLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btnHuyEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(244, 244, 244)
                        .addComponent(btnLuuEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnEditLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(pnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblTenTKEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMatKhauEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPhanQuyenEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblNhapLaiMatKhauEdit)
                            .addComponent(lblTrangThaiEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(pnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbbTrangThaiEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbPhanQuyenEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNhapLaiMatKhauEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMatKhauEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTenTKEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(pnHeadEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnEditLayout.setVerticalGroup(
            pnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEditLayout.createSequentialGroup()
                .addComponent(pnHeadEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenTKEdit)
                    .addComponent(tfTenTKEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatKhauEdit)
                    .addComponent(tfMatKhauEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(pnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNhapLaiMatKhauEdit)
                    .addComponent(tfNhapLaiMatKhauEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(pnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhanQuyenEdit)
                    .addComponent(cbbPhanQuyenEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(pnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTrangThaiEdit)
                    .addComponent(cbbTrangThaiEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(pnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHuyEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuuEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        dialogEdit.getContentPane().add(pnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, -1));

        setPreferredSize(new java.awt.Dimension(1500, 800));
        setLayout(new java.awt.BorderLayout());

        pnContent.setMinimumSize(new java.awt.Dimension(1500, 800));
        pnContent.setPreferredSize(new java.awt.Dimension(1500, 800));
        pnContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnHeader.setBackground(new java.awt.Color(255, 255, 255));

        lblQuanLiTaiKhoan.setBackground(new java.awt.Color(255, 255, 255));
        lblQuanLiTaiKhoan.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lblQuanLiTaiKhoan.setText("Quản lý tài khoản");

        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnHeaderLayout = new javax.swing.GroupLayout(pnHeader);
        pnHeader.setLayout(pnHeaderLayout);
        pnHeaderLayout.setHorizontalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeaderLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblQuanLiTaiKhoan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 782, Short.MAX_VALUE)
                .addComponent(tfTim, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        pnHeaderLayout.setVerticalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeaderLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuanLiTaiKhoan)
                    .addComponent(tfTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnContent.add(pnHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 60));

        tableTK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên tài khoản", "Mật khẩu", "Phân quyền", "Trạng thái", "Cập nhật", "Xóa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        spTable.setViewportView(tableTK);

        pnContent.add(spTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 1040, 710));

        pnLoc.setBackground(new java.awt.Color(255, 255, 255));
        pnLoc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lọc Tài Khoản", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 14))); // NOI18N
        pnLoc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPhanQuyen.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lblPhanQuyen.setText("Phân quyền");
        pnLoc.add(lblPhanQuyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        lblTrangThai.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lblTrangThai.setText("Trạng thái");
        pnLoc.add(lblTrangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        radioHoatDong.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        radioHoatDong.setText("Hoạt động");
        radioHoatDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioHoatDongActionPerformed(evt);
            }
        });
        pnLoc.add(radioHoatDong, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        radioNgungHoatDong.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        radioNgungHoatDong.setText("Ngừng hoạt động");
        radioNgungHoatDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNgungHoatDongActionPerformed(evt);
            }
        });
        pnLoc.add(radioNgungHoatDong, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        radioQuanLy.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        radioQuanLy.setText("Quản lý");
        radioQuanLy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioQuanLyActionPerformed(evt);
            }
        });
        pnLoc.add(radioQuanLy, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 160, -1));

        radioNhanVien.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        radioNhanVien.setText("Nhân viên");
        radioNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNhanVienActionPerformed(evt);
            }
        });
        pnLoc.add(radioNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        btnKhoiPhuc.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnKhoiPhuc.setText("Khôi phục");
        btnKhoiPhuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoiPhucActionPerformed(evt);
            }
        });
        pnLoc.add(btnKhoiPhuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        pnContent.add(pnLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 70, 400, 310));

        pnThem.setBackground(new java.awt.Color(255, 255, 255));
        pnThem.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thêm Tài Khoản", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 14))); // NOI18N
        pnThem.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        pnThem.setName(""); // NOI18N

        lblTenTaiKhoan.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lblTenTaiKhoan.setText("Tên tài khoản");

        lblMatKhau.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lblMatKhau.setText("Mật khẩu");

        lblNhapLaiMatKhau.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lblNhapLaiMatKhau.setText("Nhập lại mật khẩu");

        jLabel3.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel3.setText("Phân quyền");

        tfTenTaiKhoan.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N

        btnHuy.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnLuu.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        cbbPhanQuyen.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        cbbPhanQuyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản lý", "Nhân viên" }));

        pfMatKhau.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N

        pfNhapLaiMatKhau.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N

        javax.swing.GroupLayout pnThemLayout = new javax.swing.GroupLayout(pnThem);
        pnThem.setLayout(pnThemLayout);
        pnThemLayout.setHorizontalGroup(
            pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThemLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnHuy)
                    .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblTenTaiKhoan)
                        .addComponent(lblMatKhau)
                        .addComponent(lblNhapLaiMatKhau)
                        .addComponent(jLabel3)))
                .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThemLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                        .addComponent(btnLuu)
                        .addGap(85, 85, 85))
                    .addGroup(pnThemLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTenTaiKhoan)
                            .addComponent(cbbPhanQuyen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pfMatKhau)
                            .addComponent(pfNhapLaiMatKhau))
                        .addContainerGap())))
        );
        pnThemLayout.setVerticalGroup(
            pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThemLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenTaiKhoan)
                    .addComponent(tfTenTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatKhau)
                    .addComponent(pfMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNhapLaiMatKhau)
                    .addComponent(pfNhapLaiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbbPhanQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHuy)
                    .addComponent(btnLuu))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pnContent.add(pnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 390, 400, 390));

        add(pnContent, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        String keyword = tfTim.getText().trim();  // Lấy từ khóa tìm kiếm từ ô nhập liệu
    if (keyword.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập tên tài khoản cần tìm!");
        return;
    }

    DefaultTableModel model = (DefaultTableModel) tableTK.getModel();
    DefaultTableModel filteredModel = new DefaultTableModel(
        new Object[]{"STT", "Tên tài khoản", "Mật khẩu", "Phân quyền", "Trạng thái", "Cập nhật", "Xóa"}, 
        0
    );

    boolean found = false;
    for (int i = 0; i < model.getRowCount(); i++) {
        String tenTaiKhoan = model.getValueAt(i, 1).toString();  // Lấy giá trị cột 'Tên tài khoản'
        if (tenTaiKhoan.equalsIgnoreCase(keyword)) {
            // Thêm dòng tìm thấy vào model mới
            filteredModel.addRow(new Object[]{
                model.getValueAt(i, 0),
                model.getValueAt(i, 1),
                model.getValueAt(i, 2),
                model.getValueAt(i, 3),
                model.getValueAt(i, 4),
                model.getValueAt(i, 5),
                model.getValueAt(i, 6)
            });
            found = true;
            break;
        }
    }

    if (found) {
        tableTK.setModel(filteredModel);  // Hiển thị chỉ các dòng tìm thấy
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Không tìm thấy tài khoản với tên: " + keyword);
    }
    }//GEN-LAST:event_btnTimActionPerformed

    private void radioNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNhanVienActionPerformed
        locTaiKhoan();
    }//GEN-LAST:event_radioNhanVienActionPerformed

    private void radioQuanLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioQuanLyActionPerformed
        locTaiKhoan();
    }//GEN-LAST:event_radioQuanLyActionPerformed

    private void radioHoatDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioHoatDongActionPerformed
        locTaiKhoan();
    }//GEN-LAST:event_radioHoatDongActionPerformed

    private void radioNgungHoatDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNgungHoatDongActionPerformed
        locTaiKhoan();
    }//GEN-LAST:event_radioNgungHoatDongActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
      String tenTaiKhoan = tfTenTaiKhoan.getText().trim();
      String matKhau = new String(pfMatKhau.getPassword()).trim();
      String nhapLaiMatKhau = new String(pfNhapLaiMatKhau.getPassword()).trim();

      boolean phanQuyen = cbbPhanQuyen.getSelectedItem().toString().equals("Quản lý");
      boolean trangThai = radioHoatDong.isSelected();  // Lấy trạng thái từ radio button

      // Log để kiểm tra xem trạng thái đã được lấy đúng chưa
      System.out.println("Trạng thái được chọn: " + (trangThai ? "Hoạt động" : "Ngừng hoạt động"));

      if (tenTaiKhoan.isEmpty() || matKhau.isEmpty() || nhapLaiMatKhau.isEmpty()) {
          JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin.");
          return;
      }

      if (!matKhau.equals(nhapLaiMatKhau)) {
          JOptionPane.showMessageDialog(this, "Mật khẩu nhập lại không khớp.");
          return;
      }

      boolean success = taiKhoanDAO.addTaiKhoan(tenTaiKhoan, matKhau, phanQuyen, trangThai);
      if (success) {
          JOptionPane.showMessageDialog(this, "Thêm tài khoản thành công!");
          loadDataToTable();
          clearInputFields();
          setDefaultState();
      } else {
          JOptionPane.showMessageDialog(this, "Thêm tài khoản thất bại. Vui lòng thử lại.");
      }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
         clearInputFields();
         setDefaultState();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnKhoiPhucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoiPhucActionPerformed
        if (groupPhanQuyen != null) {
            groupPhanQuyen.clearSelection();  // Bỏ chọn tất cả radio button phân quyền
        }
        if (groupTrangThai != null) {
            groupTrangThai.clearSelection();  // Bỏ chọn tất cả radio button trạng thái
        }

        // Cập nhật bảng với toàn bộ dữ liệu gốc
        DefaultTableModel model = new DefaultTableModel(
            new Object[]{"STT", "Tên tài khoản", "Mật khẩu", "Phân quyền", "Trạng thái", "Cập nhật", "Xóa"},
            0
        );

        // Thêm tất cả dữ liệu gốc vào bảng
        for (Object[] row : originalData) {
            model.addRow(row);
        }

        tableTK.setModel(model);  // Cập nhật bảng

        // Gọi lại phương thức thiết lập nút sau khi cập nhật bảng
        nutChoBang();
    }//GEN-LAST:event_btnKhoiPhucActionPerformed

    private void cbbPhanQuyenEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbPhanQuyenEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbPhanQuyenEditActionPerformed

    private void tfTenTKEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTenTKEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTenTKEditActionPerformed

    private void btnLuuEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuEditActionPerformed
        // Lấy dữ liệu từ các trường
        String tenTaiKhoan = tfTenTKEdit.getText().trim();
        String matKhau = tfMatKhauEdit.getText().trim();
        String nhapLaiMatKhau = tfNhapLaiMatKhauEdit.getText().trim();
        boolean phanQuyen = cbbPhanQuyenEdit.getSelectedItem().toString().equals("Quản lý");
        boolean trangThai = cbbTrangThaiEdit.getSelectedItem().toString().equals("Hoạt động");
        
        // Kiểm tra dữ liệu nhập hợp lệ
        if (!kiemTraNhap(tenTaiKhoan, matKhau, nhapLaiMatKhau)) return;
        
        // Cập nhật tài khoản trong cơ sở dữ liệu
        boolean success = taiKhoanDAO.updateTaiKhoan(tenTaiKhoan, matKhau, phanQuyen, trangThai);
        if (success) {
            JOptionPane.showMessageDialog(this, "Cập nhật tài khoản thành công!");
            loadDataToTable();  // Cập nhật lại bảng với dữ liệu mới
            dialogEdit.dispose();  // Đóng dialog
        } else {
            JOptionPane.showMessageDialog(this, "Cập nhật tài khoản thất bại. Vui lòng thử lại.");
        }
    }//GEN-LAST:event_btnLuuEditActionPerformed

    private void clearInputFields() {
        tfTenTaiKhoan.setText("");
        pfMatKhau.setText("");
        pfNhapLaiMatKhau.setText("");
        cbbPhanQuyen.setSelectedIndex(0);
    }
    
    private void radioLoc(){
        groupPhanQuyen = new ButtonGroup();
        groupPhanQuyen.add(radioQuanLy);
        groupPhanQuyen.add(radioNhanVien);
        
        groupTrangThai = new ButtonGroup();
        groupTrangThai.add(radioHoatDong);
        groupTrangThai.add(radioNgungHoatDong);
    }
    
    private void locTaiKhoan() {
    // Lấy giá trị phân quyền và trạng thái từ radio button
    String phanQuyen = "";
    if (radioQuanLy.isSelected()) {
        phanQuyen = "Quản lý";
    } else if (radioNhanVien.isSelected()) {
        phanQuyen = "Nhân viên";
    }

    String trangThai = "";
    if (radioHoatDong.isSelected()) {
        trangThai = "Hoạt động";
    } else if (radioNgungHoatDong.isSelected()) {
        trangThai = "Ngừng hoạt động";
    }

    // Tạo model mới để chứa kết quả lọc
    DefaultTableModel filteredModel = new DefaultTableModel(
        new Object[]{"STT", "Tên tài khoản", "Mật khẩu", "Phân quyền", "Trạng thái", "Cập nhật", "Xóa"}, 
        0
    );

    int stt = 1; // Đếm số thứ tự mới sau khi lọc
    for (Object[] row : originalData) {
        String tkPhanQuyen = row[3].toString();
        String tkTrangThai = row[4].toString();

        // Kiểm tra nếu tài khoản thỏa mãn cả 2 điều kiện lọc
        boolean matchPhanQuyen = phanQuyen.isEmpty() || tkPhanQuyen.equals(phanQuyen);
        boolean matchTrangThai = trangThai.isEmpty() || tkTrangThai.equals(trangThai);

        if (matchPhanQuyen && matchTrangThai) {
            row[0] = stt++;  // Cập nhật STT
            filteredModel.addRow(row);
        }
    }

    // Cập nhật bảng với dữ liệu đã lọc
    tableTK.setModel(filteredModel);
    
    nutChoBang();
}

    private void loadDataToTable() {
        ArrayList<entity.TaiKhoan_entity> dsTaiKhoan = taiKhoanDAO.getAllTaiKhoan();
        if (dsTaiKhoan == null) {
            JOptionPane.showMessageDialog(this, "Không thể tải dữ liệu từ SQL Server!");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tableTK.getModel();
        model.setRowCount(0); // Xóa dữ liệu cũ
        originalData.clear(); // Xóa dữ liệu gốc cũ

        int stt = 1;
        for (entity.TaiKhoan_entity tk : dsTaiKhoan) {
            Object[] row = {
                stt++,
                tk.getTenDangNhap(),
                tk.getMatKhau(),
                tk.isPhanQuyen() ? "Quản lý" : "Nhân viên",
                tk.isTrangThai() ? "Hoạt động" : "Ngừng hoạt động",
                "Chỉnh sửa",  // Placeholder
                "Xóa"         // Placeholder
            };
            model.addRow(row);
            originalData.add(row);  // Lưu dữ liệu vào originalData
        }
        nutChoBang();
}
    
    public void showEditDialog(int row) {
        DefaultTableModel model = (DefaultTableModel) tableTK.getModel();

        // Lấy dữ liệu từ bảng
        String tenTaiKhoan = model.getValueAt(row, 1).toString();
        String matKhau = model.getValueAt(row, 2).toString();
        String phanQuyen = model.getValueAt(row, 3).toString();
        String trangThai = model.getValueAt(row, 4).toString();
        
//        if()
//        {
//            
//        }
        
        // Đưa dữ liệu vào các trường trên form
        tfMatKhauEdit.setText(matKhau);
        tfNhapLaiMatKhauEdit.setText(matKhau);
        tfTenTKEdit.setText(tenTaiKhoan);  // Nhập lại mật khẩu

        cbbPhanQuyenEdit.setSelectedItem(phanQuyen);
        cbbTrangThaiEdit.setSelectedItem(trangThai);

        // Hiển thị dialog
        dialogEdit.pack();
        dialogEdit.setLocationRelativeTo(this);
        dialogEdit.setVisible(true);
}

    private boolean kiemTraNhap(String tenTaiKhoan, String matKhau, String nhapLaiMatKhau) {
        if (tenTaiKhoan.isEmpty() || matKhau.isEmpty() || nhapLaiMatKhau.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin.");
            return false;
        }
        if (!matKhau.equals(nhapLaiMatKhau)) {
            JOptionPane.showMessageDialog(this, "Mật khẩu nhập lại không khớp.");
            return false;
        }
        return true;
    }
    
    private void nutChoBang() {
         // Cột "Chỉnh sửa"
        tableTK.getColumnModel().getColumn(5).setCellRenderer(
            new ButtonRenderer("/gui/icon/edit.png")
        );
        tableTK.getColumnModel().getColumn(5).setCellEditor(
            new ButtonEditor("/gui/icon/edit.png", tableTK, this, 5)
        );

        // Cột "Xóa"
        tableTK.getColumnModel().getColumn(6).setCellRenderer(
            new ButtonRenderer("/gui/icon/delete.png")
        );
        tableTK.getColumnModel().getColumn(6).setCellEditor(
            new ButtonEditor("/gui/icon/delete.png", tableTK, this, 6)
        );
    }

    public void confirmAndDeleteAccount(int row) {
        DefaultTableModel model = (DefaultTableModel) tableTK.getModel();
        String tenTaiKhoan = model.getValueAt(row, 1).toString();  // Lấy tên tài khoản.

        boolean success = taiKhoanDAO.deleteTaiKhoan(tenTaiKhoan);  // Gọi phương thức DAO.
        if (success) {
            JOptionPane.showMessageDialog(this, "Xóa tài khoản thành công!");
            model.removeRow(row);  // Xóa hàng khỏi bảng.
        } else {
            JOptionPane.showMessageDialog(this, "Xóa tài khoản thất bại. Vui lòng thử lại.");
        }
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnHuyEdit;
    private javax.swing.JButton btnKhoiPhuc;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnLuuEdit;
    private javax.swing.JButton btnTim;
    private javax.swing.JComboBox<String> cbbPhanQuyen;
    private javax.swing.JComboBox<String> cbbPhanQuyenEdit;
    private javax.swing.JComboBox<String> cbbTrangThaiEdit;
    private javax.swing.JDialog dialogEdit;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblHeadEdit;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblMatKhauEdit;
    private javax.swing.JLabel lblNhapLaiMatKhau;
    private javax.swing.JLabel lblNhapLaiMatKhauEdit;
    private javax.swing.JLabel lblPhanQuyen;
    private javax.swing.JLabel lblPhanQuyenEdit;
    private javax.swing.JLabel lblQuanLiTaiKhoan;
    private javax.swing.JLabel lblTenTKEdit;
    private javax.swing.JLabel lblTenTaiKhoan;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JLabel lblTrangThaiEdit;
    private javax.swing.JPasswordField pfMatKhau;
    private javax.swing.JPasswordField pfNhapLaiMatKhau;
    private javax.swing.JPanel pnContent;
    private javax.swing.JPanel pnEdit;
    private javax.swing.JPanel pnHeadEdit;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnLoc;
    private javax.swing.JPanel pnThem;
    private javax.swing.JRadioButton radioHoatDong;
    private javax.swing.JRadioButton radioNgungHoatDong;
    private javax.swing.JRadioButton radioNhanVien;
    private javax.swing.JRadioButton radioQuanLy;
    private javax.swing.JScrollPane spTable;
    private javax.swing.JTable tableTK;
    private javax.swing.JTextField tfMatKhauEdit;
    private javax.swing.JTextField tfNhapLaiMatKhauEdit;
    private javax.swing.JTextField tfTenTKEdit;
    private javax.swing.JTextField tfTenTaiKhoan;
    private javax.swing.JTextField tfTim;
    // End of variables declaration//GEN-END:variables
    private List<Object[]> originalData = new ArrayList<>();
}
