/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import dao.TaiKhoan_DAO;
import gui.vi.ButtonEditor;
import gui.vi.ButtonRenderer;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;


import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.SwingConstants;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableCellRenderer;

import dao.NhanVien_DAO;
import entity.TaiKhoan_entity;

import nguyenvu.components.SimpleForm;
import nguyenvu.utils.HeaderRenderer;

/**

 */
public class TaiKhoan_GUI extends SimpleForm {
    private ButtonGroup groupPhanQuyen;
    private ButtonGroup groupTrangThai;
    private TaiKhoan_DAO taiKhoanDAO = new TaiKhoan_DAO();
    private TaiKhoan_GUI taiKhoan ;
    private int totalPages = 0;
    private int currentPage = 1;
    private final int rowsPerPage = 15;
    private NhanVien_DAO nhanVienDao;
    
    /**
     * Creates new form TaiKhoan
     */
    public TaiKhoan_GUI() {
        initComponents();
        initializeDatabase();
        ysetShadowPanel();
        dialogEdit.setUndecorated(true);
        radioLoc();
        yiconForButton();
        setDefaultState();
        yloadDataToTable(currentPage,rowsPerPage); 
//        suaTimKiem();
        ySuKienFielTim();
        yCbbTenTaiKhoan();
        ySuKienPhanTrang();
    }
    
    private void initializeDatabase() {
        connectDB.connectDB.accessDataBase();
    }

    private void setDefaultState() {
        radioHoatDong.setSelected(true);  // Thiết lập trạng thái mặc định là 'Hoạt động'
        radioNgungHoatDong.setSelected(false);
        clearInputFields();  // Xóa nội dung các trường nhập liệu
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogEdit = new javax.swing.JDialog();
        pnEdit = new javax.swing.JPanel();
        lblTenTKEdit = new javax.swing.JLabel();
        lblMatKhauEdit = new javax.swing.JLabel();
        lblPhanQuyenEdit = new javax.swing.JLabel();
        lblTrangThaiEdit = new javax.swing.JLabel();
        tfMatKhauEdit = new javax.swing.JTextField();
        lblNhapLaiMatKhauEdit = new javax.swing.JLabel();
        tfNhapLaiMatKhauEdit = new javax.swing.JTextField();
        cbbPhanQuyenEdit = new javax.swing.JComboBox<>();
        cbbTrangThaiEdit = new javax.swing.JComboBox<>();
        btnHuyEdit = new javax.swing.JButton();
        btnLuuEdit = new javax.swing.JButton();
        pnHeadEdit = new javax.swing.JPanel();
        lblHeadEdit = new javax.swing.JLabel();
        tfTenTKEdit = new javax.swing.JTextField();
        pnContent = new javax.swing.JPanel();
        pnHeader = new javax.swing.JPanel();
        tfTim = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        spTable = new javax.swing.JScrollPane();
        tableTK = new javax.swing.JTable();
        pnLoc = new javax.swing.JPanel();
        lblPhanQuyen = new javax.swing.JLabel();
        lblTrangThai = new javax.swing.JLabel();
        radioHoatDong = new javax.swing.JRadioButton();
        radioNgungHoatDong = new javax.swing.JRadioButton();
        radioQuanLy = new javax.swing.JRadioButton();
        radioNhanVien = new javax.swing.JRadioButton();
        btnKhoiPhuc = new javax.swing.JButton();
        pnThem = new javax.swing.JPanel();
        lblTenTaiKhoan = new javax.swing.JLabel();
        lblMatKhau = new javax.swing.JLabel();
        lblNhapLaiMatKhau = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnHuy = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        cbbPhanQuyen = new javax.swing.JComboBox<>();
        pfMatKhau = new javax.swing.JPasswordField();
        pfNhapLaiMatKhau = new javax.swing.JPasswordField();
        cbbTenTaiKhoan = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btnLast = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        lblPageIndicator = new javax.swing.JLabel();

        pnEdit.setBackground(new java.awt.Color(245, 245, 245));

        lblTenTKEdit.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblTenTKEdit.setText("Tên tài khoản");

        lblMatKhauEdit.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblMatKhauEdit.setText("Mật khẩu");

        lblPhanQuyenEdit.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblPhanQuyenEdit.setText("Phân quyền");

        lblTrangThaiEdit.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblTrangThaiEdit.setText("Trạng thái");

        tfMatKhauEdit.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N

        lblNhapLaiMatKhauEdit.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblNhapLaiMatKhauEdit.setText("Nhập lại mật khẩu");

        tfNhapLaiMatKhauEdit.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N

        cbbPhanQuyenEdit.setBackground(new java.awt.Color(204, 204, 204));
        cbbPhanQuyenEdit.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        cbbPhanQuyenEdit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản lý", "Nhân viên" }));
        cbbPhanQuyenEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbPhanQuyenEditActionPerformed(evt);
            }
        });

        cbbTrangThaiEdit.setBackground(new java.awt.Color(204, 204, 204));
        cbbTrangThaiEdit.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        cbbTrangThaiEdit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hoạt động", "Ngừng hoạt động" }));

        btnHuyEdit.setBackground(new java.awt.Color(173, 181, 189));
        btnHuyEdit.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnHuyEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnHuyEdit.setText("Hủy");
        btnHuyEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyEditActionPerformed(evt);
            }
        });

        btnLuuEdit.setBackground(new java.awt.Color(40, 167, 69));
        btnLuuEdit.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnLuuEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnLuuEdit.setText("Lưu");
        btnLuuEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuEditActionPerformed(evt);
            }
        });

        pnHeadEdit.setBackground(new java.awt.Color(11, 101, 136));
        pnHeadEdit.setForeground(new java.awt.Color(255, 255, 255));

        lblHeadEdit.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        lblHeadEdit.setForeground(new java.awt.Color(255, 255, 255));
        lblHeadEdit.setText("Cập nhật thông tin tài khoản");

        javax.swing.GroupLayout pnHeadEditLayout = new javax.swing.GroupLayout(pnHeadEdit);
        pnHeadEdit.setLayout(pnHeadEditLayout);
        pnHeadEditLayout.setHorizontalGroup(
            pnHeadEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeadEditLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(lblHeadEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnHeadEditLayout.setVerticalGroup(
            pnHeadEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnHeadEditLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(lblHeadEdit)
                .addGap(14, 14, 14))
        );

        tfTenTKEdit.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        tfTenTKEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTenTKEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnEditLayout = new javax.swing.GroupLayout(pnEdit);
        pnEdit.setLayout(pnEditLayout);
        pnEditLayout.setHorizontalGroup(
            pnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEditLayout.createSequentialGroup()
                .addGroup(pnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnEditLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btnHuyEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(239, 239, 239)
                        .addComponent(btnLuuEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnEditLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(pnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblTenTKEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMatKhauEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPhanQuyenEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblNhapLaiMatKhauEdit)
                            .addComponent(lblTrangThaiEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(pnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbbTrangThaiEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbPhanQuyenEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNhapLaiMatKhauEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMatKhauEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTenTKEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(137, Short.MAX_VALUE))
            .addComponent(pnHeadEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnEditLayout.setVerticalGroup(
            pnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEditLayout.createSequentialGroup()
                .addComponent(pnHeadEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(pnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenTKEdit)
                    .addComponent(tfTenTKEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatKhauEdit)
                    .addComponent(tfMatKhauEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(pnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNhapLaiMatKhauEdit)
                    .addComponent(tfNhapLaiMatKhauEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(pnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhanQuyenEdit)
                    .addComponent(cbbPhanQuyenEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(pnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTrangThaiEdit)
                    .addComponent(cbbTrangThaiEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(pnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHuyEdit)
                    .addComponent(btnLuuEdit))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout dialogEditLayout = new javax.swing.GroupLayout(dialogEdit.getContentPane());
        dialogEdit.getContentPane().setLayout(dialogEditLayout);
        dialogEditLayout.setHorizontalGroup(
            dialogEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        dialogEditLayout.setVerticalGroup(
            dialogEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setMinimumSize(new java.awt.Dimension(1470, 730));
        setPreferredSize(new java.awt.Dimension(1470, 730));
        setLayout(new java.awt.BorderLayout());

        pnContent.setMinimumSize(new java.awt.Dimension(1500, 800));
        pnContent.setPreferredSize(new java.awt.Dimension(1500, 800));

        pnHeader.setBackground(new java.awt.Color(11, 101, 136));

        tfTim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfTim.setForeground(new java.awt.Color(204, 204, 204));
        tfTim.setText("Nhập Tên Tài Khoản ");
        tfTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTimActionPerformed(evt);
            }
        });

        btnTim.setBackground(new java.awt.Color(0, 123, 255));
        btnTim.setForeground(new java.awt.Color(255, 255, 255));
        btnTim.setText("Tìm kiếm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnHeaderLayout = new javax.swing.GroupLayout(pnHeader);
        pnHeader.setLayout(pnHeaderLayout);
        pnHeaderLayout.setHorizontalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeaderLayout.createSequentialGroup()
                .addContainerGap(296, Short.MAX_VALUE)
                .addComponent(tfTim, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(485, 485, 485))
        );
        pnHeaderLayout.setVerticalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeaderLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTim, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(tfTim))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableTK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên tài khoản", "Mật khẩu", "Phân quyền", "Trạng thái", "Cập nhật", "Xóa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableTK.setRowHeight(40);
        tableTK.getTableHeader().setDefaultRenderer(new HeaderRenderer());
        tableTK.getTableHeader().setPreferredSize(new Dimension(tableTK.getWidth(), 40));
        tableTK.getTableHeader().setBackground(new Color(11,101,136));
        tableTK.getTableHeader().setForeground(Color.WHITE);

        // Cài đặt độ rộng cho từng cột
        tableTK.getColumnModel().getColumn(0).setPreferredWidth(25); // Cột STT
        tableTK.getColumnModel().getColumn(1).setPreferredWidth(155); // Cột Tên khách hàng
        tableTK.getColumnModel().getColumn(2).setPreferredWidth(100); // Cột mật khẩu
        tableTK.getColumnModel().getColumn(3).setPreferredWidth(70); // Cột Phân quyền
        tableTK.getColumnModel().getColumn(4).setPreferredWidth(50); // Cột Trạng thái
        tableTK.getColumnModel().getColumn(5).setPreferredWidth(120); // Cột Cập nhật

        // Căn giữa dữ liệu trong các cột
        for (int i = 0; i < tableTK.getColumnCount(); i++) {
            DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
            renderer.setHorizontalAlignment(SwingConstants.CENTER);  // Căn giữa nội dung của cột
            tableTK.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }
        spTable.setViewportView(tableTK);

        pnLoc.setBackground(new java.awt.Color(255, 255, 255));
        pnLoc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lọc Tài Khoản", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 14))); // NOI18N

        lblPhanQuyen.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lblPhanQuyen.setText("Phân quyền");

        lblTrangThai.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lblTrangThai.setText("Trạng thái");

        radioHoatDong.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        radioHoatDong.setText("Hoạt động");
        radioHoatDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioHoatDongActionPerformed(evt);
            }
        });

        radioNgungHoatDong.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        radioNgungHoatDong.setText("Ngừng hoạt động");
        radioNgungHoatDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNgungHoatDongActionPerformed(evt);
            }
        });

        radioQuanLy.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        radioQuanLy.setText("Quản lý");
        radioQuanLy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioQuanLyActionPerformed(evt);
            }
        });

        radioNhanVien.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        radioNhanVien.setText("Nhân viên");
        radioNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNhanVienActionPerformed(evt);
            }
        });

        btnKhoiPhuc.setBackground(new java.awt.Color(108, 117, 125));
        btnKhoiPhuc.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnKhoiPhuc.setForeground(new java.awt.Color(255, 255, 255));
        btnKhoiPhuc.setText("Khôi phục");
        btnKhoiPhuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoiPhucActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnLocLayout = new javax.swing.GroupLayout(pnLoc);
        pnLoc.setLayout(pnLocLayout);
        pnLocLayout.setHorizontalGroup(
            pnLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLocLayout.createSequentialGroup()
                .addGroup(pnLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnLocLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblPhanQuyen))
                    .addGroup(pnLocLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(radioQuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnLocLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(radioNhanVien))
                    .addGroup(pnLocLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblTrangThai))
                    .addGroup(pnLocLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(radioHoatDong))
                    .addGroup(pnLocLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(radioNgungHoatDong))
                    .addGroup(pnLocLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btnKhoiPhuc, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        pnLocLayout.setVerticalGroup(
            pnLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLocLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblPhanQuyen)
                .addGap(21, 21, 21)
                .addComponent(radioQuanLy)
                .addGap(16, 16, 16)
                .addComponent(radioNhanVien)
                .addGap(16, 16, 16)
                .addComponent(lblTrangThai)
                .addGap(11, 11, 11)
                .addComponent(radioHoatDong)
                .addGap(16, 16, 16)
                .addComponent(radioNgungHoatDong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKhoiPhuc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnKhoiPhuc.getAccessibleContext().setAccessibleDescription("");

        pnThem.setBackground(new java.awt.Color(255, 255, 255));
        pnThem.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thêm Tài Khoản", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 14))); // NOI18N
        pnThem.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        pnThem.setName(""); // NOI18N

        lblTenTaiKhoan.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lblTenTaiKhoan.setText("Tên tài khoản");

        lblMatKhau.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lblMatKhau.setText("Mật khẩu");

        lblNhapLaiMatKhau.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lblNhapLaiMatKhau.setText("Nhập lại mật khẩu");

        jLabel3.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel3.setText("Phân quyền");

        btnHuy.setBackground(new java.awt.Color(173, 181, 189));
        btnHuy.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnLuu.setBackground(new java.awt.Color(40, 167, 69));
        btnLuu.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnLuu.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        cbbPhanQuyen.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        cbbPhanQuyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản lý", "Nhân viên" }));

        pfMatKhau.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N

        pfNhapLaiMatKhau.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N

        cbbTenTaiKhoan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cbbTenTaiKhoan.setPreferredSize(new java.awt.Dimension(64, 25));

        javax.swing.GroupLayout pnThemLayout = new javax.swing.GroupLayout(pnThem);
        pnThem.setLayout(pnThemLayout);
        pnThemLayout.setHorizontalGroup(
            pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThemLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThemLayout.createSequentialGroup()
                        .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNhapLaiMatKhau)
                            .addComponent(jLabel3))
                        .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnThemLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(cbbPhanQuyen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnThemLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(pfNhapLaiMatKhau))))
                    .addGroup(pnThemLayout.createSequentialGroup()
                        .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTenTaiKhoan)
                            .addComponent(lblMatKhau))
                        .addGap(47, 47, 47)
                        .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pfMatKhau)
                            .addComponent(cbbTenTaiKhoan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThemLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        pnThemLayout.setVerticalGroup(
            pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThemLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenTaiKhoan)
                    .addComponent(cbbTenTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatKhau)
                    .addComponent(pfMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNhapLaiMatKhau)
                    .addComponent(pfNhapLaiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbbPhanQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        jPanel1.setBackground(new java.awt.Color(238, 238, 238));

        lblPageIndicator.setText("Page");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblPageIndicator)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLast, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addComponent(btnNext, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addComponent(btnFirst, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addComponent(btnPrevious, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPageIndicator)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnContentLayout = new javax.swing.GroupLayout(pnContent);
        pnContent.setLayout(pnContentLayout);
        pnContentLayout.setHorizontalGroup(
            pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnContentLayout.createSequentialGroup()
                .addGroup(pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnContentLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spTable, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnLoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnContentLayout.setVerticalGroup(
            pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnContentLayout.createSequentialGroup()
                .addComponent(pnHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnContentLayout.createSequentialGroup()
                        .addComponent(pnLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnContentLayout.createSequentialGroup()
                        .addComponent(spTable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        add(pnContent, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        String keyword = tfTim.getText().trim();  // Lấy từ khóa tìm kiếm từ ô nhập liệu
    if (keyword.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập tên tài khoản cần tìm!");
        return;
    }

    DefaultTableModel model = (DefaultTableModel) tableTK.getModel();
    DefaultTableModel filteredModel = new DefaultTableModel(
        new Object[]{"STT", "Tên tài khoản", "Mật khẩu", "Phân quyền", "Trạng thái", "Cập nhật", "Xóa"}, 
        0
    );

    boolean found = false;
    for (int i = 0; i < model.getRowCount(); i++) {
        String tenTaiKhoan = model.getValueAt(i, 1).toString();  // Lấy giá trị cột 'Tên tài khoản'
        if (tenTaiKhoan.equalsIgnoreCase(keyword)) {
            // Thêm dòng tìm thấy vào model mới
            filteredModel.addRow(new Object[]{
                model.getValueAt(i, 0),
                model.getValueAt(i, 1),
                model.getValueAt(i, 2),
                model.getValueAt(i, 3),
                model.getValueAt(i, 4),
                model.getValueAt(i, 5),
                model.getValueAt(i, 6)
            });
            found = true;
            break;
        }
    }

    if (found) {
        tableTK.setModel(filteredModel);  // Hiển thị chỉ các dòng tìm thấy
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Không tìm thấy tài khoản với tên: " + keyword);
    }
    }//GEN-LAST:event_btnTimActionPerformed

    private void radioNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNhanVienActionPerformed
        locTaiKhoan();
    }//GEN-LAST:event_radioNhanVienActionPerformed

    private void radioQuanLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioQuanLyActionPerformed
        locTaiKhoan();
    }//GEN-LAST:event_radioQuanLyActionPerformed

    private void radioHoatDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioHoatDongActionPerformed
        locTaiKhoan();
    }//GEN-LAST:event_radioHoatDongActionPerformed

    private void radioNgungHoatDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNgungHoatDongActionPerformed
        locTaiKhoan();
    }//GEN-LAST:event_radioNgungHoatDongActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
      String tenTaiKhoan = (String) cbbTenTaiKhoan.getSelectedItem();
      String matKhau = new String(pfMatKhau.getPassword()).trim();
      String nhapLaiMatKhau = new String(pfNhapLaiMatKhau.getPassword()).trim();

      boolean phanQuyen = cbbPhanQuyen.getSelectedItem().toString().equals("Quản lý");
      boolean trangThai = radioHoatDong.isSelected();  // Lấy trạng thái từ radio button

      // Log để kiểm tra xem trạng thái đã được lấy đúng chưa
      System.out.println("Trạng thái được chọn: " + (trangThai ? "Hoạt động" : "Ngừng hoạt động"));

      if (tenTaiKhoan.isEmpty() || matKhau.isEmpty() || nhapLaiMatKhau.isEmpty()) {
          JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin.");
          return;
      }

      if (!matKhau.equals(nhapLaiMatKhau)) {
          JOptionPane.showMessageDialog(this, "Mật khẩu nhập lại không khớp.");
          return;
      }

      boolean success = taiKhoanDAO.addTaiKhoan(tenTaiKhoan, matKhau, phanQuyen, trangThai);
      if (success) {
          JOptionPane.showMessageDialog(this, "Thêm tài khoản thành công!");
          yloadDataToTable(currentPage,rowsPerPage);
          clearInputFields();
          setDefaultState();
      } else {
          JOptionPane.showMessageDialog(this, "Thêm tài khoản thất bại. Vui lòng thử lại.");
      }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
         clearInputFields();
         setDefaultState();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnKhoiPhucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoiPhucActionPerformed
        if (groupPhanQuyen != null) {
            groupPhanQuyen.clearSelection();  // Bỏ chọn tất cả radio button phân quyền
        }
        if (groupTrangThai != null) {
            groupTrangThai.clearSelection();  // Bỏ chọn tất cả radio button trạng thái
        }

        // Cập nhật bảng với toàn bộ dữ liệu gốc
        DefaultTableModel model = new DefaultTableModel(
            new Object[]{"STT", "Tên tài khoản", "Mật khẩu", "Phân quyền", "Trạng thái", "Cập nhật", "Xóa"},
            0
        );

        // Thêm tất cả dữ liệu gốc vào bảng
        for (Object[] row : originalData) {
            model.addRow(row);
        }

        tableTK.setModel(model);  // Cập nhật bảng

        // Gọi lại phương thức thiết lập nút sau khi cập nhật bảng
        nutChoBang();
    }//GEN-LAST:event_btnKhoiPhucActionPerformed

    private void cbbPhanQuyenEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbPhanQuyenEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbPhanQuyenEditActionPerformed

    private void tfTenTKEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTenTKEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTenTKEditActionPerformed

    private void btnLuuEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuEditActionPerformed
        // Lấy dữ liệu từ các trường
        String tenTaiKhoan = tfTenTKEdit.getText().trim();
        String matKhau = tfMatKhauEdit.getText().trim();
        String nhapLaiMatKhau = tfNhapLaiMatKhauEdit.getText().trim();
        boolean phanQuyen = cbbPhanQuyenEdit.getSelectedItem().toString().equals("Quản lý");
        boolean trangThai = cbbTrangThaiEdit.getSelectedItem().toString().equals("Hoạt động");
        
        // Kiểm tra dữ liệu nhập hợp lệ
        if (!kiemTraNhap(tenTaiKhoan, matKhau, nhapLaiMatKhau)) return;
        
        // Cập nhật tài khoản trong cơ sở dữ liệu
        boolean success = taiKhoanDAO.updateTaiKhoan(tenTaiKhoan, matKhau, phanQuyen, trangThai);
        if (success) {
            JOptionPane.showMessageDialog(this, "Cập nhật tài khoản thành công!");
            yloadDataToTable(currentPage,rowsPerPage);  // Cập nhật lại bảng với dữ liệu mới
            dialogEdit.dispose();  // Đóng dialog
        } else {
            JOptionPane.showMessageDialog(this, "Cập nhật tài khoản thất bại. Vui lòng thử lại.");
        }
    }//GEN-LAST:event_btnLuuEditActionPerformed

    private void btnHuyEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyEditActionPerformed
        dialogEdit.setVisible(false);
    }//GEN-LAST:event_btnHuyEditActionPerformed

    private void tfTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTimActionPerformed

    private void clearInputFields() {
        pfMatKhau.setText("");
        pfNhapLaiMatKhau.setText("");
        cbbPhanQuyen.setSelectedIndex(0);
    }
    
    private void radioLoc(){
        groupPhanQuyen = new ButtonGroup();
        groupPhanQuyen.add(radioQuanLy);
        groupPhanQuyen.add(radioNhanVien);
        
        groupTrangThai = new ButtonGroup();
        groupTrangThai.add(radioHoatDong);
        groupTrangThai.add(radioNgungHoatDong);
    }
    
    private void locTaiKhoan() {
    // Lấy giá trị phân quyền và trạng thái từ radio button
    String phanQuyen = "";
    if (radioQuanLy.isSelected()) {
        phanQuyen = "Quản lý";
    } else if (radioNhanVien.isSelected()) {
        phanQuyen = "Nhân viên";
    }

    String trangThai = "";
    if (radioHoatDong.isSelected()) {
        trangThai = "Hoạt động";
    } else if (radioNgungHoatDong.isSelected()) {
        trangThai = "Ngừng hoạt động";
    }

    // Tạo model mới để chứa kết quả lọc
    DefaultTableModel filteredModel = new DefaultTableModel(
        new Object[]{"STT", "Tên tài khoản", "Mật khẩu", "Phân quyền", "Trạng thái", "Cập nhật", "Xóa"}, 
        0
    );

    int stt = 1; // Đếm số thứ tự mới sau khi lọc
    for (Object[] row : originalData) {
        String tkPhanQuyen = row[3].toString();
        String tkTrangThai = row[4].toString();

        // Kiểm tra nếu tài khoản thỏa mãn cả 2 điều kiện lọc
        boolean matchPhanQuyen = phanQuyen.isEmpty() || tkPhanQuyen.equals(phanQuyen);
        boolean matchTrangThai = trangThai.isEmpty() || tkTrangThai.equals(trangThai);

        if (matchPhanQuyen && matchTrangThai) {
            row[0] = stt++;  // Cập nhật STT
            filteredModel.addRow(row);
        }
    }

    // Cập nhật bảng với dữ liệu đã lọc
    tableTK.setModel(filteredModel);
    
    nutChoBang();
}
    
    public void ysetShadowPanel(){
        pnHeader.putClientProperty(FlatClientProperties.STYLE, ""
                + "border:0,0,0,0,$Component.borderColor,,26");
        pnHeadEdit.putClientProperty(FlatClientProperties.STYLE, ""
                + "border:0,0,0,0,$Component.borderColor,,26");
    }
    
    public void yCbbTenTaiKhoan(){
        nhanVienDao = new NhanVien_DAO();
        ArrayList<String> dsMaNV = nhanVienDao.getAllMaNhanVien();
        for (String maNV : dsMaNV) {
            cbbTenTaiKhoan.addItem(maNV);  // Thêm từng mã nhân viên vào ComboBox
        }
    }
    
    public void ySuKienPhanTrang(){
        btnFirst.addActionListener(e -> {
	        currentPage = 1;
	        yloadDataToTable(currentPage, rowsPerPage);
	    });

                btnPrevious.addActionListener(e -> {
                    if (currentPage > 1) {
                        currentPage--;
                        yloadDataToTable(currentPage, rowsPerPage);
                    }
                });

                btnNext.addActionListener(e -> {
                    if (currentPage < totalPages) {
                        currentPage++;
                        yloadDataToTable(currentPage, rowsPerPage);
                    }
                });

	    btnLast.addActionListener(e -> {
	        currentPage = totalPages;
	        yloadDataToTable(currentPage, rowsPerPage);
	    });
    }
    
    public void yiconForButton(){
        btnTim.setIcon(new FlatSVGIcon("gui/icon/vi_search_white.svg",0.2f));
        btnKhoiPhuc.setIcon(new FlatSVGIcon("gui/icon/vi_restore_white.svg",0.125f));
        btnHuy.setIcon(new FlatSVGIcon("gui/icon/vi_restore_white.svg",0.125f));
        btnLuu.setIcon(new FlatSVGIcon("gui/icon/vi_add_white.svg",0.125f));
        btnHuyEdit.setIcon(new FlatSVGIcon("gui/icon/vi_restore_white.svg",0.125f));
        btnLuuEdit.setIcon(new FlatSVGIcon("gui/icon/vi_add_white.svg",0.125f));
        btnFirst.setIcon(new FlatSVGIcon("gui/icon/first-page.svg",0.02f));
        btnPrevious.setIcon(new FlatSVGIcon("gui/icon/pre-page.svg",0.01f));
        btnNext.setIcon(new FlatSVGIcon("gui/icon/next-page.svg",0.01f));
        btnLast.setIcon(new FlatSVGIcon("gui/icon/last-page.svg",0.02f));
    }
    
    private void yloadDataToTable(int currentPage, int rowsPerPage) {
        DefaultTableModel model = (DefaultTableModel) tableTK.getModel();
        model.setRowCount(0); // Xóa dữ liệu hiện tại trong bảng

        try {
            ArrayList<TaiKhoan_entity> dsTaiKhoan = taiKhoanDAO.getAllTaiKhoan();
            if (dsTaiKhoan == null) {
                JOptionPane.showMessageDialog(this, "Không thể tải dữ liệu từ SQL Server!");
                return;
            }

            // Tính tổng số trang
            int totalPages = (int) Math.ceil((double) dsTaiKhoan.size() / rowsPerPage);

            // Tính toán chỉ số bắt đầu và kết thúc
            int start = (currentPage - 1) * rowsPerPage;
            int end = Math.min(start + rowsPerPage, dsTaiKhoan.size());

            // Hiển thị dữ liệu của trang hiện tại
            int stt = start + 1; // Đếm từ dòng hiện tại
            for (int i = start; i < end; i++) {
                TaiKhoan_entity tk = dsTaiKhoan.get(i);
                Object[] row = {
                    stt++,
                    tk.getTenDangNhap(),
                    tk.getMatKhau(),
                    tk.isPhanQuyen() ? "Quản lý" : "Nhân viên",
                    tk.isTrangThai() ? "Hoạt động" : "Ngừng hoạt động",
                    "Chỉnh sửa", // Placeholder
                    "Xóa"        // Placeholder
                };
                model.addRow(row);
            }

            // Cập nhật chỉ số trang lên giao diện
            lblPageIndicator.setText(currentPage + " / " + totalPages);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu lên bảng!");
        }
    }

    
    public void showEditDialog(int row) {
        DefaultTableModel model = (DefaultTableModel) tableTK.getModel();

        // Lấy dữ liệu từ bảng
        String tenTaiKhoan = model.getValueAt(row, 1).toString();
        String matKhau = model.getValueAt(row, 2).toString();
        String phanQuyen = model.getValueAt(row, 3).toString();
        String trangThai = model.getValueAt(row, 4).toString();
        

        
        // Đưa dữ liệu vào các trường trên form
        tfMatKhauEdit.setText(matKhau);
        tfNhapLaiMatKhauEdit.setText(matKhau);
        tfTenTKEdit.setText(tenTaiKhoan);  // Nhập lại mật khẩu

        cbbPhanQuyenEdit.setSelectedItem(phanQuyen);
        cbbTrangThaiEdit.setSelectedItem(trangThai);

        // Hiển thị dialog
        dialogEdit.pack();
        dialogEdit.setLocationRelativeTo(this);
        dialogEdit.setVisible(true);
}

    private boolean kiemTraNhap(String tenTaiKhoan, String matKhau, String nhapLaiMatKhau) {
        if (tenTaiKhoan.isEmpty() || matKhau.isEmpty() || nhapLaiMatKhau.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin.");
            return false;
        }
        if (!matKhau.equals(nhapLaiMatKhau)) {
            JOptionPane.showMessageDialog(this, "Mật khẩu nhập lại không khớp.");
            return false;
        }
        return true;
    }
    
    private void nutChoBang() {
         // Cột "Chỉnh sửa"
        tableTK.getColumnModel().getColumn(5).setCellRenderer(
            new ButtonRenderer("/gui/icon/edit.png")
        );
        tableTK.getColumnModel().getColumn(5).setCellEditor(
            new ButtonEditor("/gui/icon/edit.png", tableTK, this, 5)
        );

        // Cột "Xóa"
        tableTK.getColumnModel().getColumn(6).setCellRenderer(
            new ButtonRenderer("/gui/icon/delete.png")
        );
        tableTK.getColumnModel().getColumn(6).setCellEditor(
            new ButtonEditor("/gui/icon/delete.png", tableTK, this, 6)
        );
    }

    public void confirmAndDeleteAccount(int row) {
        DefaultTableModel model = (DefaultTableModel) tableTK.getModel();
        String tenTaiKhoan = model.getValueAt(row, 1).toString();  // Lấy tên tài khoản.

        boolean success = taiKhoanDAO.deleteTaiKhoan(tenTaiKhoan);  // Gọi phương thức DAO.
        if (success) {
            JOptionPane.showMessageDialog(this, "Xóa tài khoản thành công!");
            model.removeRow(row);  // Xóa hàng khỏi bảng.
        } else {
            JOptionPane.showMessageDialog(this, "Xóa tài khoản thất bại. Vui lòng thử lại.");
        }
    }
    
    public void ySuKienFielTim(){
        tfTim.addFocusListener(new FocusAdapter() {
			@Override
			public void focusGained(FocusEvent e) {
				if (tfTim.getText().equals("Nhập Tên Tài Khoản ")) {
					tfTim.setText("");
					tfTim.setForeground(Color.GRAY); // Đặt lại màu văn bản xám cho placeholder
				} else {
					tfTim.setForeground(Color.BLACK); // Đặt màu văn bản bình thường nếu có nội dung
				}
			}

			@Override
			public void focusLost(FocusEvent e) {
				if (tfTim.getText().equals("")) {
					tfTim.setForeground(Color.GRAY);
					tfTim.setText("Nhập Tên Tài Khoản "); // Nếu không có nội dung thì để trống
				}
			}
		});
    }
    
//            public void suaTimKiem(){
//                tfTim = new JTextField();
//		tfTim.setFont(new Font("Arial", Font.PLAIN, 15));
//		tfTim.setBackground(new Color(11, 101, 136));
//		tfTim.setBounds(240, 16, 537, 32);
//		pnHeader.add(tfTim);
//		tfTim.setColumns(10);
//		// Tạo đường viền chỉ có phía dưới
//		Border bottomBorder = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.BLACK);
//		tfTim.setBorder(bottomBorder);
//
//		// Placeholder behavior khi JTextField mất hoặc có focus
//		tfTim.addFocusListener(new FocusAdapter() {
//			@Override
//			public void focusGained(FocusEvent e) {
//				if (tfTim.getText().equals("Nhập Tên Hoặc Mã Sản Phẩm")) {
//					tfTim.setText("");
//					tfTim.setForeground(Color.GRAY); // Đặt lại màu văn bản xám cho placeholder
//				} else {
//					tfTim.setForeground(Color.BLACK); // Đặt màu văn bản bình thường nếu có nội dung
//				}
//			}
//
//			@Override
//			public void focusLost(FocusEvent e) {
//				if (tfTim.getText().equals("")) {
//					tfTim.setForeground(Color.GRAY);
//					tfTim.setText("Nhập Tên Hoặc Mã Sản Phẩm"); // Nếu không có nội dung thì để trống
//				}
//			}
//		});
//
//		// Khởi tạo với placeholder
//		tfTim.setText("Nhập Tên Hoặc Mã Sản Phẩm"); // Hiện placeholder
//		tfTim.setForeground(new Color(255, 255, 255)); // Đặt màu xám cho văn bản placeholder
//    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnHuyEdit;
    private javax.swing.JButton btnKhoiPhuc;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnLuuEdit;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnTim;
    private javax.swing.JComboBox<String> cbbPhanQuyen;
    private javax.swing.JComboBox<String> cbbPhanQuyenEdit;
    private javax.swing.JComboBox<String> cbbTenTaiKhoan;
    private javax.swing.JComboBox<String> cbbTrangThaiEdit;
    private javax.swing.JDialog dialogEdit;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHeadEdit;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblMatKhauEdit;
    private javax.swing.JLabel lblNhapLaiMatKhau;
    private javax.swing.JLabel lblNhapLaiMatKhauEdit;
    private javax.swing.JLabel lblPageIndicator;
    private javax.swing.JLabel lblPhanQuyen;
    private javax.swing.JLabel lblPhanQuyenEdit;
    private javax.swing.JLabel lblTenTKEdit;
    private javax.swing.JLabel lblTenTaiKhoan;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JLabel lblTrangThaiEdit;
    private javax.swing.JPasswordField pfMatKhau;
    private javax.swing.JPasswordField pfNhapLaiMatKhau;
    private javax.swing.JPanel pnContent;
    private javax.swing.JPanel pnEdit;
    private javax.swing.JPanel pnHeadEdit;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnLoc;
    private javax.swing.JPanel pnThem;
    private javax.swing.JRadioButton radioHoatDong;
    private javax.swing.JRadioButton radioNgungHoatDong;
    private javax.swing.JRadioButton radioNhanVien;
    private javax.swing.JRadioButton radioQuanLy;
    private javax.swing.JScrollPane spTable;
    private javax.swing.JTable tableTK;
    private javax.swing.JTextField tfMatKhauEdit;
    private javax.swing.JTextField tfNhapLaiMatKhauEdit;
    private javax.swing.JTextField tfTenTKEdit;
    private javax.swing.JTextField tfTim;
    // End of variables declaration//GEN-END:variables
    private List<Object[]> originalData = new ArrayList<>();
}
