/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import dao.TaiKhoan_DAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.table.DefaultTableModel;
import nguyenvu.components.SimpleForm;

/**

 */
public class TaiKhoan_GUI extends SimpleForm {

    private ButtonGroup groupPhanQuyen;
    private ButtonGroup groupTrangThai;
    private TaiKhoan_DAO taiKhoanDAO = new TaiKhoan_DAO();
    private TaiKhoan_GUI taiKhoan ;
    
    /**
     * Creates new form TaiKhoan
     */
    public TaiKhoan_GUI() {
        initComponents();
        initializeDatabase();
        radioLoc();
        loadDataToTable(); 
}
    private void initializeDatabase() {
    connectDB.connectDB.accessDataBase();  // Khởi tạo kết nối khi cần thiết
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnContent = new javax.swing.JPanel();
        pnHeader = new javax.swing.JPanel();
        lblQuanLiTaiKhoan = new javax.swing.JLabel();
        tfTim = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        spTable = new javax.swing.JScrollPane();
        tableTK = new javax.swing.JTable();
        pnLoc = new javax.swing.JPanel();
        lblPhanQuyen = new javax.swing.JLabel();
        lblTrangThai = new javax.swing.JLabel();
        radioHoatDong = new javax.swing.JRadioButton();
        radioNgungHoatDong = new javax.swing.JRadioButton();
        radioQuanLy = new javax.swing.JRadioButton();
        radioNhanVien = new javax.swing.JRadioButton();
        btnKhoiPhuc = new javax.swing.JButton();
        pnThem = new javax.swing.JPanel();
        lblTenTaiKhoan = new javax.swing.JLabel();
        lblMatKhau = new javax.swing.JLabel();
        lblNhapLaiMatKhau = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfTenTaiKhoan = new javax.swing.JTextField();
        btnHuy = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        cbbPhanQuyen = new javax.swing.JComboBox<>();
        pfMatKhau = new javax.swing.JPasswordField();
        pfNhapLaiMatKhau = new javax.swing.JPasswordField();

        setPreferredSize(new java.awt.Dimension(1500, 800));
        setLayout(new java.awt.BorderLayout());

        pnContent.setMinimumSize(new java.awt.Dimension(1500, 800));
        pnContent.setPreferredSize(new java.awt.Dimension(1500, 800));
        pnContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnHeader.setBackground(new java.awt.Color(255, 255, 255));

        lblQuanLiTaiKhoan.setBackground(new java.awt.Color(255, 255, 255));
        lblQuanLiTaiKhoan.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lblQuanLiTaiKhoan.setText("Quản lý tài khoản");

        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnHeaderLayout = new javax.swing.GroupLayout(pnHeader);
        pnHeader.setLayout(pnHeaderLayout);
        pnHeaderLayout.setHorizontalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeaderLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblQuanLiTaiKhoan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 782, Short.MAX_VALUE)
                .addComponent(tfTim, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        pnHeaderLayout.setVerticalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeaderLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuanLiTaiKhoan)
                    .addComponent(tfTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnContent.add(pnHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 60));

        tableTK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên tài khoản", "Mật khẩu", "Phân quyền", "Trạng thái", "Cập nhật", "Xóa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        spTable.setViewportView(tableTK);

        pnContent.add(spTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 1040, 710));

        pnLoc.setBackground(new java.awt.Color(255, 255, 255));
        pnLoc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lọc Tài Khoản", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 14))); // NOI18N
        pnLoc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPhanQuyen.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lblPhanQuyen.setText("Phân quyền");
        pnLoc.add(lblPhanQuyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        lblTrangThai.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lblTrangThai.setText("Trạng thái");
        pnLoc.add(lblTrangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        radioHoatDong.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        radioHoatDong.setText("Hoạt động");
        radioHoatDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioHoatDongActionPerformed(evt);
            }
        });
        pnLoc.add(radioHoatDong, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        radioNgungHoatDong.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        radioNgungHoatDong.setText("Ngừng hoạt động");
        radioNgungHoatDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNgungHoatDongActionPerformed(evt);
            }
        });
        pnLoc.add(radioNgungHoatDong, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        radioQuanLy.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        radioQuanLy.setText("Quản lý");
        radioQuanLy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioQuanLyActionPerformed(evt);
            }
        });
        pnLoc.add(radioQuanLy, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 160, -1));

        radioNhanVien.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        radioNhanVien.setText("Nhân viên");
        radioNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNhanVienActionPerformed(evt);
            }
        });
        pnLoc.add(radioNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        btnKhoiPhuc.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnKhoiPhuc.setText("Khôi phục");
        btnKhoiPhuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoiPhucActionPerformed(evt);
            }
        });
        pnLoc.add(btnKhoiPhuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        pnContent.add(pnLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 70, 400, 310));

        pnThem.setBackground(new java.awt.Color(255, 255, 255));
        pnThem.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thêm Tài Khoản", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 14))); // NOI18N
        pnThem.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        pnThem.setName(""); // NOI18N

        lblTenTaiKhoan.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lblTenTaiKhoan.setText("Tên tài khoản");

        lblMatKhau.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lblMatKhau.setText("Mật khẩu");

        lblNhapLaiMatKhau.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lblNhapLaiMatKhau.setText("Nhập lại mật khẩu");

        jLabel3.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel3.setText("Phân quyền");

        tfTenTaiKhoan.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N

        btnHuy.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnLuu.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        cbbPhanQuyen.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        cbbPhanQuyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản lý", "Nhân viên" }));

        pfMatKhau.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N

        pfNhapLaiMatKhau.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N

        javax.swing.GroupLayout pnThemLayout = new javax.swing.GroupLayout(pnThem);
        pnThem.setLayout(pnThemLayout);
        pnThemLayout.setHorizontalGroup(
            pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThemLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnHuy)
                    .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblTenTaiKhoan)
                        .addComponent(lblMatKhau)
                        .addComponent(lblNhapLaiMatKhau)
                        .addComponent(jLabel3)))
                .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThemLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                        .addComponent(btnLuu)
                        .addGap(85, 85, 85))
                    .addGroup(pnThemLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTenTaiKhoan)
                            .addComponent(cbbPhanQuyen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pfMatKhau)
                            .addComponent(pfNhapLaiMatKhau))
                        .addContainerGap())))
        );
        pnThemLayout.setVerticalGroup(
            pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThemLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenTaiKhoan)
                    .addComponent(tfTenTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatKhau)
                    .addComponent(pfMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNhapLaiMatKhau)
                    .addComponent(pfNhapLaiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbbPhanQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHuy)
                    .addComponent(btnLuu))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pnContent.add(pnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 390, 400, 390));

        add(pnContent, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        String keyword = tfTim.getText().trim();  // Lấy từ khóa tìm kiếm từ ô nhập liệu
    if (keyword.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập tên tài khoản cần tìm!");
        return;
    }

    DefaultTableModel model = (DefaultTableModel) tableTK.getModel();
    DefaultTableModel filteredModel = new DefaultTableModel(
        new Object[]{"STT", "Tên tài khoản", "Mật khẩu", "Phân quyền", "Trạng thái", "Cập nhật", "Xóa"}, 
        0
    );

    boolean found = false;
    for (int i = 0; i < model.getRowCount(); i++) {
        String tenTaiKhoan = model.getValueAt(i, 1).toString();  // Lấy giá trị cột 'Tên tài khoản'
        if (tenTaiKhoan.equalsIgnoreCase(keyword)) {
            // Thêm dòng tìm thấy vào model mới
            filteredModel.addRow(new Object[]{
                model.getValueAt(i, 0),
                model.getValueAt(i, 1),
                model.getValueAt(i, 2),
                model.getValueAt(i, 3),
                model.getValueAt(i, 4),
                model.getValueAt(i, 5),
                model.getValueAt(i, 6)
            });
            found = true;
            break;
        }
    }

    if (found) {
        tableTK.setModel(filteredModel);  // Hiển thị chỉ các dòng tìm thấy
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Không tìm thấy tài khoản với tên: " + keyword);
    }
    }//GEN-LAST:event_btnTimActionPerformed

    private void radioNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNhanVienActionPerformed
        locTaiKhoan();
    }//GEN-LAST:event_radioNhanVienActionPerformed

    private void radioQuanLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioQuanLyActionPerformed
        locTaiKhoan();
    }//GEN-LAST:event_radioQuanLyActionPerformed

    private void radioHoatDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioHoatDongActionPerformed
        locTaiKhoan();
    }//GEN-LAST:event_radioHoatDongActionPerformed

    private void radioNgungHoatDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNgungHoatDongActionPerformed
        locTaiKhoan();
    }//GEN-LAST:event_radioNgungHoatDongActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
       String tenTaiKhoan = tfTenTaiKhoan.getText().trim();
       String matKhau = new String(pfMatKhau.getPassword()).trim();
       boolean phanQuyen = cbbPhanQuyen.getSelectedItem().toString().equals("Quản lý");
       boolean trangThai = radioHoatDong.isSelected();

       if (tenTaiKhoan.isEmpty() || matKhau.isEmpty()) {
           javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin.");
           return;
       }

       boolean success = taiKhoanDAO.addTaiKhoan(tenTaiKhoan, matKhau, phanQuyen, trangThai);
       if (success) {
           javax.swing.JOptionPane.showMessageDialog(this, "Thêm tài khoản thành công!");
           loadDataToTable();  // Cập nhật bảng
       } else {
           javax.swing.JOptionPane.showMessageDialog(this, "Thêm tài khoản thất bại.");
       }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
         clearInputFields();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnKhoiPhucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoiPhucActionPerformed
        if (groupPhanQuyen != null) {
        groupPhanQuyen.clearSelection();  // Bỏ chọn tất cả radio button phân quyền
    }
    if (groupTrangThai != null) {
        groupTrangThai.clearSelection();  // Bỏ chọn tất cả radio button trạng thái
    }

    // Cập nhật bảng với toàn bộ dữ liệu gốc
    DefaultTableModel model = new DefaultTableModel(
        new Object[]{"STT", "Tên tài khoản", "Mật khẩu", "Phân quyền", "Trạng thái", "Cập nhật", "Xóa"},
        0
    );

    // Thêm tất cả dữ liệu gốc vào bảng
    for (Object[] row : originalData) {
        model.addRow(row);
    }

    tableTK.setModel(model);  // Cập nhật bảng
    }//GEN-LAST:event_btnKhoiPhucActionPerformed
    
    private void clearInputFields() {
    tfTenTaiKhoan.setText("");
    pfMatKhau.setText("");
    pfNhapLaiMatKhau.setText("");
    cbbPhanQuyen.setSelectedIndex(0);
    radioHoatDong.setSelected(true);  // Mặc định chọn 'Hoạt động'
}
    
    private void radioLoc(){
        groupPhanQuyen = new ButtonGroup();
        groupPhanQuyen.add(radioQuanLy);
        groupPhanQuyen.add(radioNhanVien);
        
        groupTrangThai = new ButtonGroup();
        groupTrangThai.add(radioHoatDong);
        groupTrangThai.add(radioNgungHoatDong);
    }
    
    private void locTaiKhoan() {
    // Lấy phân quyền được chọn
    String phanQuyen = radioQuanLy.isSelected() ? "Quản lý" : 
                       radioNhanVien.isSelected() ? "Nhân viên" : "";

    // Lấy trạng thái được chọn
    String trangThai = radioHoatDong.isSelected() ? "Hoạt động" : 
                       radioNgungHoatDong.isSelected() ? "Ngừng hoạt động" : "";

    // Tạo model mới để chứa các kết quả lọc
    DefaultTableModel filteredModel = new DefaultTableModel(
        new Object[]{"STT", "Tên tài khoản", "Mật khẩu", "Phân quyền", "Trạng thái", "Cập nhật", "Xóa"}, 
        0
    );

    // Duyệt qua dữ liệu gốc và thêm các dòng thỏa mãn điều kiện vào model
    for (Object[] row : originalData) {
        String tkPhanQuyen = row[3].toString();  // Lấy giá trị 'Phân quyền'
        String tkTrangThai = row[4].toString();  // Lấy giá trị 'Trạng thái'

        // Kiểm tra nếu tài khoản thỏa mãn cả phân quyền và trạng thái đã chọn
        if ((phanQuyen.isEmpty() || tkPhanQuyen.equals(phanQuyen)) &&
            (trangThai.isEmpty() || tkTrangThai.equals(trangThai))) {
            filteredModel.addRow(row);
        }
    }

    // Cập nhật bảng với dữ liệu đã lọc
    tableTK.setModel(filteredModel);
}

    private void loadDataToTable() {
    ArrayList<entity.TaiKhoan> dsTaiKhoan = taiKhoanDAO.getAllTaiKhoan();  // Gọi từ DAO
    if (dsTaiKhoan == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Không thể tải dữ liệu từ SQL Server!");
        return;
    }

    DefaultTableModel model = (DefaultTableModel) tableTK.getModel();
    model.setRowCount(0);  // Xóa dữ liệu cũ

    // Duyệt từng đối tượng TaiKhoan và thêm vào JTable
    int stt = 1;
    for (entity.TaiKhoan tk : dsTaiKhoan) {
        Object[] row = {
            stt++,  // Số thứ tự
            tk.getTenDangNhap(),
            tk.getMatKhau(),
            tk.isPhanQuyen() ? "Quản lý" : "Nhân viên",
            tk.isTrangThai() ? "Hoạt động" : "Ngừng hoạt động",
            "Cập nhật",  // Giả lập nút "Cập nhật"
            "Xóa"  // Giả lập nút "Xóa"
        };
        model.addRow(row);
    }
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnKhoiPhuc;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnTim;
    private javax.swing.JComboBox<String> cbbPhanQuyen;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblNhapLaiMatKhau;
    private javax.swing.JLabel lblPhanQuyen;
    private javax.swing.JLabel lblQuanLiTaiKhoan;
    private javax.swing.JLabel lblTenTaiKhoan;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JPasswordField pfMatKhau;
    private javax.swing.JPasswordField pfNhapLaiMatKhau;
    private javax.swing.JPanel pnContent;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnLoc;
    private javax.swing.JPanel pnThem;
    private javax.swing.JRadioButton radioHoatDong;
    private javax.swing.JRadioButton radioNgungHoatDong;
    private javax.swing.JRadioButton radioNhanVien;
    private javax.swing.JRadioButton radioQuanLy;
    private javax.swing.JScrollPane spTable;
    private javax.swing.JTable tableTK;
    private javax.swing.JTextField tfTenTaiKhoan;
    private javax.swing.JTextField tfTim;
    // End of variables declaration//GEN-END:variables
    private List<Object[]> originalData = new ArrayList<>();
}
