/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package nguyenvu.forms;

import com.formdev.flatlaf.FlatClientProperties;
import java.awt.Color;
import java.awt.Component;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Random;
import javax.swing.JLabel;
import javax.swing.JPanel;
import net.miginfocom.swing.MigLayout;
import nguyenvu.components.SimpleForm;
import nguyenvu.utils.DateCalculator;
import raven.chart.ChartLegendRenderer;
import raven.chart.data.category.DefaultCategoryDataset;
import raven.chart.line.LineChart;

/**
 *
 * @author HP
 */
public class DashboardForm extends SimpleForm {
    
    /**
     * Creates new customizer TestDashboard
     */
    public DashboardForm() {
        init();
    }
    
    @Override
    public void formRefresh() {
        lineChart.startAnimation();
    }

    @Override
    public void formInitAndOpen() {
//        System.out.println("init and open");
    }

    @Override
    public void formOpen() {
        System.out.println("Open");
    }
    
    private void init() {
        setLayout(new MigLayout("wrap,fill,gap 10", "fill"));
        createLineChart();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    private void createPreviewNofication() {
        JPanel pnOutOfStock = new JPanel();
        JLabel header1 = new JLabel("Sản phẩm sắp hết hạn");
    }
    
    
    private void createLineChart() {
        lineChart = new LineChart();
        lineChart.setChartType(LineChart.ChartType.CURVE);
        lineChart.putClientProperty(FlatClientProperties.STYLE, ""
                + "border:5,5,5,5,$Component.borderColor,,20");
        add(lineChart, "height 500");
        createLineChartData();
    }
    
    private void createLineChartData() {
        categoryDataset = new DefaultCategoryDataset<>();
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        Random ran = new Random();
        int randomDate = 30;
        for (int i = 1; i <= randomDate; i++) {
            String date = df.format(cal.getTime());
            categoryDataset.addValue(ran.nextInt(700) + 5, "Income", date);
            categoryDataset.addValue(ran.nextInt(700) + 5, "Expense", date);
            categoryDataset.addValue(ran.nextInt(700) + 5, "Profit", date);

            cal.add(Calendar.DATE, 1);
        }

        Date date = null;
        Date dateEnd = null;
        /**
         * Control the legend we do not show all legend
         */
        try {
            date = df.parse(categoryDataset.getColumnKey(0));
            dateEnd = df.parse(categoryDataset.getColumnKey(categoryDataset.getColumnCount() - 1));

            DateCalculator dcal = new DateCalculator(date, dateEnd);
            long diff = dcal.getDifferenceDays();

            double d = Math.ceil((diff / 10f));
            lineChart.setLegendRenderer(new ChartLegendRenderer() {
                @Override
                public Component getLegendComponent(Object legend, int index) {
                    if (index % d == 0) {
                        return super.getLegendComponent(legend, index);
                    } else {
                        return null;
                    }
                }
            });
        } catch (ParseException e) {
            System.err.println(e);
        }
        
        String strDate = df.format(date);
        String strDateEnd = df.format(dateEnd);

        lineChart.setCategoryDataset(categoryDataset);
        lineChart.getChartColor().addColor(Color.decode("#38bdf8"), Color.decode("#fb7185"), Color.decode("#34d399"));
        JLabel header = new JLabel("Thống kê tổng quan từ " + strDate + " đến " + strDateEnd); 
        header.putClientProperty(FlatClientProperties.STYLE, ""
                + "font:bold +10");
        lineChart.setHeader(header);
    }

    private LineChart lineChart;
    private DefaultCategoryDataset<String, String> categoryDataset;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
