/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package nguyenvu.utils;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.google.zxing.BinaryBitmap;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.NotFoundException;
import com.google.zxing.Result;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;
import dao.BanHang_DAO;
import entity.ChiTietHoaDon;
import entity.SanPham_entity;
import gui.BanHang;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.concurrent.atomic.AtomicLong;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.SwingConstants;
import nguyenvu.components.SimpleForm;
import org.opencv.core.Core;
import org.opencv.core.Mat;
import org.opencv.core.MatOfByte;
import org.opencv.imgcodecs.Imgcodecs;
import org.opencv.videoio.VideoCapture;
import raven.alerts.MessageAlerts;
import javax.sound.sampled.*;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class FilterProductSearchPanel extends SimpleForm {
    private BanHang banHang;
    private JPopupMenu menu;
    private JTable table;

    public FilterProductSearchPanel(JPopupMenu menu, BanHang banHang, JTable table) {
        this.menu = menu;
        this.banHang = banHang;
        this.table = table;
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBarcode = new javax.swing.JButton();
        btnQrcode = new javax.swing.JButton();

        btnBarcode.setText("Scan barcode");
        btnBarcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarcodeActionPerformed(evt);
            }
        });

        btnQrcode.setText("Scan qrcode");
        btnQrcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQrcodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBarcode, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(btnQrcode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQrcode, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        btnBarcode.setIcon(new FlatSVGIcon("gui/icon/barcode.svg", 0.5f));
        btnBarcode.setHorizontalAlignment(SwingConstants.LEFT);
        btnQrcode.setIcon(new FlatSVGIcon("gui/icon/scan.svg", 0.5f));
        btnQrcode.setHorizontalAlignment(SwingConstants.LEFT);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarcodeActionPerformed
        // TODO add your handling code here:
        if(menu != null) {
            this.setVisible(false);
        }
        
        startBarcodeScanner();
    }//GEN-LAST:event_btnBarcodeActionPerformed

    private void btnQrcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQrcodeActionPerformed
        // TODO add your handling code here:
        if(menu != null) {
            this.setVisible(false);
        }
        
        String maHD = GenerateCode.startQrcodeScanner();
        if(maHD.isEmpty()) {
            MessageAlerts.getInstance().showMessage("Lỗi", "Mã hóa đơn không hợp lệ!", MessageAlerts.MessageType.ERROR);
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        
        ArrayList<ChiTietHoaDon> listCTHD = BanHang_DAO.getListCTHD(maHD);
        if (listCTHD == null || listCTHD.isEmpty()) {
            MessageAlerts.getInstance().showMessage("Lỗi", "Không tìm thấy chi tiết hóa đơn.", MessageAlerts.MessageType.ERROR);
            return;
        }
        
        System.out.println("listCTHD.size(): " + listCTHD.size());
        
        try {
            for(ChiTietHoaDon cthd : listCTHD) {
                SanPham_entity sp = new BanHang_DAO().getSP(cthd.getMaSP());
                ImageIcon iiSP = new ImageIcon(getClass().getResource(sp.getHinhAnhSP()));
                Image imgSP = iiSP.getImage().getScaledInstance(60, 60, Image.SCALE_SMOOTH);
                
                Object[] rowData = new Object[] {
                    model.getRowCount() + 1, // STT
                    new ImageIcon(imgSP), // hinhAnh
                    sp.getMaSP(), // maSP
                    sp.getTenSP(), // tenSP
                    sp.getDonViTinh(), // donVi
                    cthd.getSoLuongSanPham(), // soLuong 

                    sp.getGia(), // donGia
                    cthd.getSoLuongSanPham() * sp.getGia()
                };
                model.addRow(rowData);
            }
        } catch (Exception e) {
        }
        
        banHang.updateLblSoLuongSP();
    }//GEN-LAST:event_btnQrcodeActionPerformed

    private void startBarcodeScanner() {
        System.loadLibrary("opencv_java4100");
        VideoCapture camera = new VideoCapture(0);

        if (!camera.isOpened()) {
            MessageAlerts.getInstance().showMessage("Lỗi", "Không thể mở camera!", MessageAlerts.MessageType.ERROR);
            return;
        }

        Mat frame = new Mat();
        JFrame window = new JFrame("Quét mã barcode");
        window.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        JLabel label = new JLabel();
        window.add(label);
        window.setSize(800, 700);
        window.setResizable(false);
        window.setLocationRelativeTo(null);
        window.setVisible(true);
        
        final int scanCooldown = 1000;
        AtomicLong lastScanTime = new AtomicLong(0);
        
        javax.swing.Timer timer = new javax.swing.Timer(30, e -> {
            if (camera.read(frame)) {
                try {
                    BufferedImage bufferedImage = matToBufferedImage(frame);
                    BufferedImage resizedImage = resizeImage(bufferedImage, label.getWidth(), label.getHeight());
                    label.setIcon(new ImageIcon(resizedImage));

                    long currentTime = System.currentTimeMillis();
                    if(currentTime - lastScanTime.get() >= scanCooldown) {
                        String barcodeText = decodeBarcode(bufferedImage);
                        if (barcodeText != null) {
                            playSound("barcodeSP/barcodeSound.wav");
                            banHang.addProductToTable(new BanHang_DAO().getSP(barcodeText));
    //                        MessageAlerts.getInstance().showMessage("Mã sản phẩm: " + barcodeText, "Barcode Scanned", MessageAlerts.MessageType.SUCCESS);
    //                        camera.release();
    //                        window.dispose();
                             lastScanTime.set(currentTime);
                        }
                    }
                    
                    
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        });

        timer.start();

        window.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                camera.release();
                timer.stop();
            }
        });
        
    }

    // Hàm chuyển đổi Mat sang BufferedImage
    private BufferedImage matToBufferedImage(Mat mat) throws Exception {
        MatOfByte mob = new MatOfByte();
        Imgcodecs.imencode(".jpg", mat, mob);
        return ImageIO.read(new ByteArrayInputStream(mob.toArray()));
    }

    // Hàm giải mã barcode từ BufferedImage
    private String decodeBarcode(BufferedImage bufferedImage) {
        try {
            BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(new BufferedImageLuminanceSource(bufferedImage)));
            Result result = new MultiFormatReader().decode(bitmap);
            return result.getText(); // Trả về mã sản phẩm từ barcode
        } catch (NotFoundException e) {
            return null; // Không tìm thấy mã barcode trong khung hình
        }
    }
    
    private BufferedImage resizeImage(BufferedImage img, int newW, int newH) {
        Image tmp = img.getScaledInstance(newW, newH, Image.SCALE_SMOOTH);
        BufferedImage resized = new BufferedImage(newW, newH, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2d = resized.createGraphics();
        g2d.drawImage(tmp, 0, 0, null);
        g2d.dispose();
        return resized;
    }
    
    private void playSound(String filePath) throws IOException {
        try {
            File soundFile = new File(filePath);
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundFile);
            Clip clip = AudioSystem.getClip();
            clip.open(audioStream);
            clip.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBarcode;
    private javax.swing.JButton btnQrcode;
    // End of variables declaration//GEN-END:variables
}
